### ISSUE TITLE
Poor contrast on highlight

### ISSUE THREAD

**Issue by TimsManter** [EliverLara/Nordic#10]
Generally this theme looks very well, especially with Newaita icons but I noticed some places with not enough contrast for text to be clearly readable. E.g. in Geary selected message with light highlight and white text isn't visible enough. In Pamac selected item could have a little bit more contrast too.

Nordic - Geary | Nordic - Pamac
--- | ---
![screenshot from 2018-11-20 20-56-35](https://user-images.githubusercontent.com/5507688/48800028-e908f600-ed08-11e8-94c6-a7b25c14082e.png) | ![screenshot from 2018-11-20 20-56-57](https://user-images.githubusercontent.com/5507688/48800056-00e07a00-ed09-11e8-8d0f-4b9dc62163e0.png)

I compared this to Qogir theme that I was using before:

Qogir - Geary | Qogir - Pamac
--- | ---
![screenshot from 2018-11-20 21-01-07](https://user-images.githubusercontent.com/5507688/48800230-7cdac200-ed09-11e8-8d31-5cd1bd2b05cd.png) | ![screenshot from 2018-11-20 21-02-48](https://user-images.githubusercontent.com/5507688/48800241-82d0a300-ed09-11e8-8f6e-e5fbcbe1dcbe.png)

Please notice that Qogir uses different color for rich-text item highlight.

Opinions may vary so a very simple generation/installation script (like in some themes) could be helpful to select base color(s). For example I would likely to choose nord10 instead of nord7 as an accent/highlight color.

Some kind of "brightness multiplier" for background colors (something like Sass's darken() func) would be also cool because I think this theme is just a bit too light.

**Comment by EliverLara** [comment]
Hi, thanks for the feedback!, you're right, I'm going to check the contrast color, I'll try to add an installation script in the future, for now you can easily edit the `.scss` files to fit your needs.

**Comment by romildo** [comment]
The installation script will be welcome. Then packagers could install from source.
