### ISSUE TITLE
World clock

### ISSUE THREAD

**Issue by maurizio-fanigliulo** [EliverLara/Nordic#100]
In the theme Nordiic-bluish-accent world clock indicator is too dark and therefore almost invisible.

**Comment by EliverLara** [comment]
Hi, could you provide a screenshot, please?

**Comment by maurizio-fanigliulo** [comment]
Hi, this is a screenshot.
    -- 
      
        Maurizio Fanigliulo
        ✉
        
          maurizio.fanigliulo@gmail.com
        ♻
        
          Rispetta l'ambiente. Non stampare questa e-mail se non è
          necessario.

**Comment by EliverLara** [comment]
@maurizio-fanigliulo sorry but there is no screenshot in your comment.

**Comment by hiruko-san** [comment]
![Screenshot from 2021-06-24 01-59-07](https://user-images.githubusercontent.com/61776667/123145833-c43f0700-d44c-11eb-865e-514c16334e4f.png)
![Screenshot from 2021-06-24 02-01-39](https://user-images.githubusercontent.com/61776667/123146141-1a13af00-d44d-11eb-8e8e-923b07c32eaa.png)

Hi, attached is the screenshot showing if I apply both the App theme and the Shell theme then the font in Gnome shell World Clock will turn dark and hard to see.

If I were to only enable it as shell theme then the font will display as normal, in white.

I've tested this with both versions of Nordic, Nordic Polar, and Nordic bluish.
