### ISSUE TITLE
Error in gtk-3.0 CSS

### ISSUE THREAD

**Issue by lfom** [EliverLara/Nordic#101]
Probably it was caused by a merge and or other `git` command used improperly (the first two lines and last one should be removed):
```
<<<<<<< HEAD
=======
@define-color fg_color #d8dee9;
@define-color text_color #d8dee9;
@define-color bg_color #3b4252;
@define-color base_color #2e3440;
@define-color selected_bg_color #4c566a;
@define-color selected_fg_color #fff;
@define-color unfocused_fg_color #8a909e;
@define-color unfocused_text_color #d8dee9;
@define-color unfocused_bg_color #3b4252;
@define-color unfocused_base_color #303643;
@define-color unfocused_selected_bg_color #4c566a;
@define-color unfocused_selected_fg_color #d8dee9;
>>>>>>> 7ba8a5d... Rebuild theme
```
This results in this error in the log:

`Theme parsing error: gtk.css:43:0: Expected a valid selector`

**Comment by EliverLara** [comment]
Hi, this erro log does not occur on my side, Are you sure you are using the latest version?

**Comment by lfom** [comment]
I have downloaded latest version from https://www.gnome-look.org/p/1267246/ (from 2020.11.17 as of now) and the broken code is still there. The error is not shown in the Gnome Shell log, as it is a GTK app theme problem, it is shown in `journalctl -f`. Just to make it clear, the problematic file is:
**Nordic-darker-standard-buttons/gtk-3.0**

**Comment by EliverLara** [comment]
> Just to make it clear, the problematic file is: Nordic-darker-standard-buttons/gtk-3.0/gtk.css

Thanks for the info! I've reuploaded the corrected file.

**Comment by lfom** [comment]
Latest version is fixed, thanks. I hope the source was also updated so next versions will be OK. Chers.
