### ISSUE TITLE
SDDM loading error

### ISSUE THREAD

**Issue by mstr-Wolf** [EliverLara/Nordic#103]
I received the following error message after setting Nordic theme for SDDM and system reboot:

> The current theme cannot be loaded due to the errors below, please select another theme.
>
> file:///usr/share/sddm/themes/Nordic/Main.qml:126:26: Type Login unavailable
> file:///usr/share/sddm/themes/Nordic/Login.qml:47:5: Typer Input unavailable
> file:///usr/share/sddm/themes/Nordic/components/Input.qml:7:5: Cannot assign to non-existent property "placeholderTextColor"
>
Can someone help me to fix it, please? I'm using Debian 10 (buster) with KDE Plasma

**Comment by EliverLara** [comment]
Hi, what is your `Qt` version? (run `qtdiag` in your terminal)

**Comment by mstr-Wolf** [comment]
Thank you for the fast answer =)
> qtdiag: could not find a Qt installation of ''
