### ISSUE TITLE
Rounded window corners don't display correctly on KDE

### ISSUE THREAD

**Issue by rddunphy** [EliverLara/Nordic#104]
On KDE I've noticed an issue with the rounded corners of windows, where sometimes a square outline can be seen. It appears to be filling in the "transparent" background from a point near but not directly at the corner - so the colour appears to change as you move the window. In the screenshot below you can see a green top left corner and orange bottom right corner. It's not always that obvious, but I think if you look closely you can even see this issue in the [screenshot used in the README](https://github.com/EliverLara/Nordic/blob/master/Art/nordic.png).

![image](https://user-images.githubusercontent.com/10012625/102102794-1e1e9e80-3e24-11eb-9f4b-73d9f034ce39.png)

This might be related to #93, but I notice it much more with windows than context menus.

Thanks for maintaining this theme, I'm really enjoying it!

Operating System: Kubuntu 20.10
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.14.2

**Comment by EliverLara** [comment]
This is an issue with aurorae as you can see [here](https://bugs.kde.org/show_bug.cgi?id=395725)

**Comment by rddunphy** [comment]
Good to know, thanks!
