### ISSUE TITLE
Active line in text fields is unreadable due to very low contrast

### ISSUE THREAD

**Issue by narwhalofages** [EliverLara/Nordic#108]
For some reason, the active line in editable text fields has very low contrast between the text and active line, making it very difficult to read. This makes it next to impossible to see what you are typing as you enter it; selecting text on the active line makes it readable again. Issue appears in both Nordic and Nordic darker. 

### Examples

**Gedit**
![Screenshot from 2021-01-12 11-00-04](https://user-images.githubusercontent.com/16219814/104361162-f411d800-54c6-11eb-9ba7-3471276b8396.png)

**Marker** (Markdown editor)
![Screenshot from 2021-01-12 11-01-05](https://user-images.githubusercontent.com/16219814/104361178-f96f2280-54c6-11eb-9ce1-3cc54c57ed8b.png)

Settings in **Gnome Tweak Tool**
![Screenshot from 2021-01-12 11-03-35](https://user-images.githubusercontent.com/16219814/104361327-26bbd080-54c7-11eb-8071-3086d1c84f52.png)

### My system environment
Desktop Environment: Gnome 3.38.3
Window Manager: GDM/Mutter
EliverLara/Nordic theme version 1.9.0

**Neofetch** (for software versions, if necessary)
![Screenshot from 2021-01-12 11-06-32](https://user-images.githubusercontent.com/16219814/104361946-050f1900-54c8-11eb-9b54-7018a111d53f.png)

**Comment by EliverLara** [comment]
Hi @narwhalofages , they both seem to be app issues when you use a dark theme, as you can see [here](https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/29) and [here](https://github.com/fabiocolacio/Marker/issues/195).

Arc dark | Adwaita dark 
------ | ----- 
![Captura de pantalla de 2021-03-01 16-04-32](https://user-images.githubusercontent.com/9838260/109566040-eaf5be00-7aa8-11eb-8b94-cc4dbc9e59e9.png)|![Captura de pantalla de 2021-03-01 16-05-08](https://user-images.githubusercontent.com/9838260/109566064-f47f2600-7aa8-11eb-8618-37beffde53af.png)
