### ISSUE TITLE
Menus not dark themed

### ISSUE THREAD

**Issue by prdanelli** [EliverLara/Nordic#109]
Firstly, thank you for the theme, it beautiful.

Are the menus supposed to be themed as well, the other GUI components? Mine are still light themed, even though i'm using the Nordic Dark theme. 

![image](https://user-images.githubusercontent.com/1199977/104966409-bb976000-59d8-11eb-929f-39a0e0e331aa.png)

![image](https://user-images.githubusercontent.com/1199977/104966431-c520c800-59d8-11eb-852f-eaa6182ee3b6.png)

**Comment by EliverLara** [comment]
Hi, it looks like you haven't applied the gnome-shell theme.

**Comment by prdanelli** [comment]
@EliverLara Thank you for responding. I downloaded the theme from [here](https://www.gnome-look.org/p/1267246/) and applied it with Gnome Tweaks, but just to be sure I ran the other commands listed on the Gnome Look page: 

```
gsettings set org.gnome.desktop.interface gtk-theme Nordic

gsettings set org.gnome.desktop.wm.preferences theme Nordic
```
I've restarted multiple times since installing the theme. Am I missing a step?

**Comment by EliverLara** [comment]
Yes, you must set the gnome-shell theme to use Nordic, it's recommended to use a tweak-tool to do it.

**Comment by prdanelli** [comment]
@EliverLara Thank you, yes that has been how I have been installing and activating the theme, however the menus have never been the dark colour that i see using the default pop-dark themes.

**Comment by lfom** [comment]
@prdanelli Do you have User Themes extension installed? It is not installed by default on Pop!_OS, and it is required for theming the Shell.

**Comment by prdanelli** [comment]
@lfom that was it! I'm sorry to waste every ones time. I'm pretty new to Linux and must have missed the line in the readme.
