### ISSUE TITLE
App icons and docker icons aren't like in the preview

### ISSUE THREAD

**Issue by aviadtamir** [EliverLara/Nordic#110]
the applications and dock icons stay the same even after downloading all the files and extracting them to ~/.icons and ~/.themes and picking the Nordic theme in tweaks 

![Screenshot from 2021-01-19 21-25-11](https://user-images.githubusercontent.com/24754559/105082948-f19e1800-5a9c-11eb-9009-a7d714100fd1.png)

**Comment by EliverLara** [comment]
Hi, try using [this](https://www.gnome-look.org/p/1473069/)

**Comment by aviadtamir** [comment]
Thanks!

**Comment by mokafolio** [comment]
The link is dead, what was the solution?

**Comment by mastern2k3** [comment]
> Hi, try using [this](https://www.gnome-look.org/p/1473069/)

The link became broken, what were you referring to?
