### ISSUE TITLE
Will the color of the buttons and radio box be nordic?

### ISSUE THREAD

**Issue by kennak0** [EliverLara/Nordic#112]
It's a very favorite theme and is healed every day. thanks you. I am using nordic-darker.

I would like to inform you that there are some colors that I am interested in.
The color of buttons such as the font setting screen.
Is this going to be a nordic color?

![Screenshot from 2021-02-12 23-24-12](https://user-images.githubusercontent.com/22781228/107780827-8d643080-6d8a-11eb-9bf3-3dd50bcbb733.png)
![Screenshot from 2021-02-12 23-24-13](https://user-images.githubusercontent.com/22781228/107780850-91904e00-6d8a-11eb-8ebe-b1247aa06917.png)
![Screenshot from 2021-02-12 23-24-35](https://user-images.githubusercontent.com/22781228/107780996-bbe20b80-6d8a-11eb-8ba6-2780d7053e92.png)

As a Japanese user, please understand that the screenshots are unfamiliar characters.

**Comment by EliverLara** [comment]
Hi, Do you mean the color of check/radio buttons? if so, they actually uses nord colors: 

![Captura de pantalla de 2021-03-01 15-34-45](https://user-images.githubusercontent.com/9838260/109562480-1033fd80-7aa4-11eb-88d2-2454408a978e.png)

**Comment by kennak0** [comment]
yes. Hidpi monitor.

**Comment by kennak0** [comment]
Thank you for your quick response.
I have tried the version released on 2021-03-15.
Checkboxes and radio buttons are okay. It is perfect.
Just one more thing...

The theme used in the screenshot above is Nordic-darker, but only the OK button on the right side of the top screenshot looks like Nordic-bluish-accent.

Can this also be fixed?
