### ISSUE TITLE
Blurred top panel in Gnome Shell

### ISSUE THREAD

**Issue by otaj** [EliverLara/Nordic#114]
Hi, there seems to be a problem of top panel icons, which are blurred in your theme.
The first image is from Nordic (with Roboto, Slight Hinting and Standard Antialiasing - that's how the options are called in Gnome Tweaks), second image is from Adwaita (Default Gnome shell theme). You can see the difference in icons in Nordic, they are not crisp at all, but somewhat blurry. I first noticed it at the Bluetooth Icon, but it is visible in all the standard icons

![nordic](https://user-images.githubusercontent.com/6065855/108496372-3ab6d700-72aa-11eb-858a-55d87291731e.png)
![adwaita](https://user-images.githubusercontent.com/6065855/108496397-42767b80-72aa-11eb-8e09-1d5deb35178e.png)

**Comment by EliverLara** [comment]
Fixed!
