### ISSUE TITLE
Package notice && archlinux user installation tutorial requirements 

### ISSUE THREAD

**Issue by hamkido** [EliverLara/Nordic#116]
Hello @EliverLara, Your theme is awesome! Thank you.
this issue is a notice:
I have packaged this theme in the Arch user repository.
https://aur.archlinux.org/packages/nordic-theme/
Archlinux users can install this theme with aur helper.
Just like yay -S nordic-theme
The package name
|------------------|
|nordic-theme|
|nordic-dark-theme|
|nordic-blue-theme|
|nordic-blues-theme|
|nordic-dark-standard-button-theme|
|nordic-blues-standard-button-theme|

I want added PR for readme add archlinux user install tutorial.

**Comment by REmerald** [comment]
@hamkido [The packages with this theme for Plasma, sddm and Kvantum got deleted](https://github.com/chaotic-aur/packages/issues/3249). Could you recreate those packages (maybe without git, e.g. `plasma5-themes-nordic`, `sddm-theme-nordic`, `kvantum-theme-nordic`)?

**Comment by hamkido** [comment]
Sorry, I was busy moving some time ago. I'll deal with it this weekend.
