### ISSUE TITLE
GTK4 and Gnome Shell 40 support?

### ISSUE THREAD

**Issue by codic12** [EliverLara/Nordic#120]
Gtk4 is fairly new, but fully stable. Gnome Shell 40 is beta, but coming out as a stable release soon (within a week or two), so it would be great if you added support for both.

Adwaita can be used as a reference theme, like is done for GTK3. TIA!

**Comment by yudjinn** [comment]
adding to this, using any of the nordic themes as the applications theme in gnome 40 causes the terminal to graphically break. goes transparent and starts tearing

**Comment by EliverLara** [comment]
Support for `gnome-shell v40`  added

**Comment by Enayaaa** [comment]
I am so glad there is a gtk4 support! Great work on that. I have this issue with the extensions app where the window has got some extra padding inside where it needs to be, the border I have is added by pop-shell around windows.

![image](https://user-images.githubusercontent.com/50826990/146174608-5a69807c-f798-4a67-b5fb-1c13864ec000.png)
