### ISSUE TITLE
How do i configure my Dolphin to be like your screenshot?

### ISSUE THREAD

**Issue by hrqmonteiro** [EliverLara/Nordic#126]
![Screenshot_20210429_235944](https://user-images.githubusercontent.com/17055027/116643353-47f5df00-a947-11eb-8e52-25fa1bf413da.png)

I installed your theme and it look nothing like yours, on the kde-store website:

![image](https://user-images.githubusercontent.com/17055027/116643385-547a3780-a947-11eb-957f-bfabfbe48bff.png)

**Comment by EliverLara** [comment]
Hi, for better looking please use this theme with [Kvantum](https://github.com/tsujan/Kvantum/tree/master/Kvantum) engine and install the [Nordic theme for kvantum](https://store.kde.org/p/1326272/)

**Comment by hrqmonteiro** [comment]
> Hi, for better looking please use this theme with [Kvantum](https://github.com/tsujan/Kvantum/tree/master/Kvantum) engine and install the [Nordic theme for kvantum](https://store.kde.org/p/1326272/)

I did that, it still doesn't like near close to your  screenshots. It looks like my screenshots i posted.

**Comment by EliverLara** [comment]
@hrqmonteiro in your screenshots seems like you haven't applied the kvantum theme, Did you use kvantum-manager to set Nordic theme?
