### ISSUE TITLE
Low Contrast on Gnome 40 Shell

### ISSUE THREAD

**Issue by Gambloide** [EliverLara/Nordic#128]
# Context

**Gnome Shell Version:** 40.1.0
**Theme:** Nordic Darker (2021-05-06 release from https://www.gnome-look.org/s/Gnome/p/1267246/)

# Description

I am personally having difficulties recognizing selected/highlighted items in the Gnome shell since I updated from Fedora 33 to Fedora 34, introducing Gnome 40+. I am not suggesting to bring the contrast as high up as the default in Gnome, but increasing it somewhat to make it easier to recognize what we are interacting with.

Previously this color choice was not a problem, since it was an overlay over the wallpaper. With Gnome 40, this search view is not overlaying the wallpaper anymore.

I have not tested other Nordic theme flavors, yet.

For comparison Nordic vs Default:

Nordic Darker Gnome 40 Shell
![Screenshot from 2021-05-09 14-56-18](https://user-images.githubusercontent.com/5939852/117573289-537b9f80-b0d7-11eb-90b7-659f60add741.png)

Default Gnome 40 Shell
![Screenshot from 2021-05-09 15-01-32](https://user-images.githubusercontent.com/5939852/117573325-8c1b7900-b0d7-11eb-81ca-aab18bfd1121.png)

**Comment by EliverLara** [comment]
Hi, Gnome shell v40 support has been added so now it looks better.
