### ISSUE TITLE
KDE: Low logout screen contrast

### ISSUE THREAD

**Issue by gchamon** [EliverLara/Nordic#132]
Currently unreadable...

![image](https://user-images.githubusercontent.com/9471861/120912696-dc9add80-c667-11eb-9e8a-b26a78a7e85e.png)

Changing Rectangle opacity to something around 0.6 alleviates the issue:

![image](https://user-images.githubusercontent.com/9471861/120912716-0b18b880-c668-11eb-82b8-4c79106fc14f.png)

https://github.com/EliverLara/Nordic/blob/master/kde/look-and-feel/contents/logout/Logout.qml#L108-L114

**Comment by EliverLara** [comment]
Thanks for your suggestion, I've implemented it.
