### ISSUE TITLE
Opaque bar when it should be transparent around Gnome 40 dock in overview, with blur-my-shell

### ISSUE THREAD

**Issue by Araly** [EliverLara/Nordic#134]
see https://github.com/aunetx/blur-my-shell/issues/89

When using the blur-my-shell extension, the bottom of the screen should be transparent and blurry, but it's opaque instead. This only happens when using blur-my-shell, with the Nordic theme selected in User Themes extension.

Maybe it's just because the theme is not GTK4 ?

**Comment by EliverLara** [comment]
Hi, Are you using the latest release? it includes support to gnome-shell v40

**Comment by Araly** [comment]
just downloaded the latest update, works perfectly, thanks a lot
