### ISSUE TITLE
Building from source?

### ISSUE THREAD

**Issue by HumblePresent** [EliverLara/Nordic#137]
This theme looks fantastic but I'm interested in changing some of the colors. I'm not well acquainted with CSS/SCSS at all so I might be wrong about this, but it looks like I could change the color definitions in `_colors.scss` and they would propogate to the rest of the theme after building. Thing is I'm not sure how to build from source. Like I said, I'm an absolute novice when it comes to CSS/SCSS so I tried `sass gtk.scss` but that generated an error. Basically, my question is how to build this theme from source the way you would to create a release?

**Comment by EliverLara** [comment]
Hi, take a look to #73

**Comment by HumblePresent** [comment]
Hi, thanks for getting back to me. I tried installing `npm` and following the instructions in #73 but I get errors when running `npm install` in the theme directory. What version of `npm` and `libsass` are you using?

**Comment by HumblePresent** [comment]
Also tried building with plain sass by running `sass gtk.scss` but get the following error
```
Error: compound selectors may no longer be extended.
Consider `@extend %selected_items, :disabled` instead.
See http://bit.ly/ExtendCompound for details.

    ╷
125 │     selection { @extend %selected_items:disabled; }
    │                         ^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  widgets/_base-states.scss 125:25  root stylesheet
```

**Comment by aperullo** [comment]
For anyone seeing this issue after in the future, dart-sass (what @HumblePresent is using above) deprecated this syntax in a [breaking change](https://sass-lang.com/documentation/breaking-changes/extend-compound). However if you use rubygem-sass, this only throws a warning, and it will compile successfully. For me that was `dnf install rubygem-sass`.

**Comment by HumblePresent** [comment]
Yeah I came to the same conclusion by using the [ruby-sass](https://archlinux.org/packages/community/any/ruby-sass/) package on Arch.
