### ISSUE TITLE
Support for Pop!_OS 21.04 with COSMIC?

### ISSUE THREAD

**Issue by humanplayer2** [EliverLara/Nordic#138]
First, of course, thank you very much for the work on this great theme! I've loved using it on Ubuntu.

I have now migrated to Pop!_OS with their recent 21.04 release. Here, a several of the interface components default to a light theme (I guess Adwaita light), including the newly-added Launcher and drop-downs from the top bar (calendar, power menu, indicator menus).

See screenshot for an example with the launcher (the orange marking of gedit is it being marked as selected window).

I very much hope the theme could be made to support these elements. Else the price of migration will be high indeed!
![Screenshot from 2021-07-02 11-22-37](https://user-images.githubusercontent.com/220154/124253237-1b696980-db28-11eb-818d-a3d595c24088.png)

**Comment by AndreBClark** [comment]
I Second this. I forked the repo and have been trying to edit the theme to implement this myself. I have been able to adjust a few things using classes referenced in [this reddit post](https://www.reddit.com/r/pop_os/comments/obcidg/quick_guide_how_to_match_your_dock_and/ )

**Comment by humanplayer2** [comment]
I'm sorry, I was an absolute idiot. It's been too long since I did a proper clean install: I forgot to set the shell theme,

I also see that the theme doesn't apply to the applications background, but I think that changing that will become available only later. Maybe it's the same with the dock?

I'll close this now. I'm embarrassed by my oversight.
