### ISSUE TITLE
Text in notifications isn't contrasting

### ISSUE THREAD

**Issue by fastovst** [EliverLara/Nordic#14]
This issue appeared on Ubuntu 18.10 with Gnome 3.30.1. Notifications are not readable since the text is too dark.
![nordic-shell](https://user-images.githubusercontent.com/14261148/49581555-fa820d00-f95a-11e8-8a3c-a8b15e2983ec.jpg)

**Comment by EliverLara** [comment]
Hi, Could you check that this is not a conflict with another gdm theme? that's what usually happens in this situation, as you can see [here](https://github.com/EliverLara/Sweet/issues/15) and [here](https://github.com/EliverLara/Sweet/issues/6).

**Comment by northernwulf** [comment]
I checked another shells and they change notification text color, but when I apply Nordic shell then it looks like on the screenshot. I think it is a problem with Nordic shell.

**Comment by Drk01** [comment]
I have the same problem with a raw instalation of Ubuntu 18.10, Can you help me?

**Comment by jakbyte** [comment]
I have the same problem with a recent installation of Ubuntu 19.04.

**Comment by fastovst** [comment]
@EliverLara Hi, sorry for not responding for such a long time. I have switched to Manjaro for my own reasons and haven't had similar issues since. I guess I can close this issue now, however, some people are still facing the same problem, then perhaps they could provide some feedback on this.

**Comment by jakbyte** [comment]
How would I check if it is a conflict with another gdm theme?
