### ISSUE TITLE
Small artifacts in gnome

### ISSUE THREAD

**Issue by TahsinTariq** [EliverLara/Nordic#140]
Tested on OS: 
Pop 20.10
Pop 21.04

Problem:
Scrolling in the folder, settings or other applications produces these small dashed lines on the top and bottom. It can be seen in this image just beside the Desktop and Documents folder.
![image](https://user-images.githubusercontent.com/62146852/124379323-23680b80-dcd8-11eb-9d73-f0d52e729709.png)
It's more apparent here as seen on both top and bottom in settings.
![image](https://user-images.githubusercontent.com/62146852/124379381-75109600-dcd8-11eb-8f53-d86e8eead570.png)

**Comment by AndreBClark** [comment]
I am seeing this too. unsure where it's coming from. I have been looking into the CSS and I'm still unable to find the culprit. are you using nordic dark as well? does this still exist when you try other variations such as bluish accent or regular nordic? I'm gonna be testing that as well to see if I can isolate this issue. 

Sorry, I don't have any good news regarding this.

**Comment by TahsinTariq** [comment]
Yes, I'm using nordic dark. I've tested this on the bluish accent and the artifacts are still there.

**Comment by EliverLara** [comment]
Hi, that's not really an issue, those dashed lines mean the content can be scrolled in that direction, it is a GTK feature.
If you want to disable it, the easiest way is by setting the `background-image `property to `none` on line [581 of gtk-3.0/_drawing.scss file](https://github.com/EliverLara/Nordic/blob/138d81f289be2926989258fade6c0a805ae06baa/gtk-3.0/_drawing.scss#L581) and then just recompile the whole theme using `sass`.

**Comment by TahsinTariq** [comment]
Thanks, had no idea that was a feature.
