### ISSUE TITLE
Dark Polar Variant

### ISSUE THREAD

**Issue by svnset** [EliverLara/Nordic#15]
Hello :)

First of all great work on this theme. Alot of fans of the nord color palette are desperately waiting for a decent native nord gtk theme. I love the dark variant so far. Do you think it's possible to make a Polar version of the dark variant? The polar highlighting colors look perfect :)

If necessary I would offer my help too.

**Comment by EliverLara** [comment]
Hi, What exactly do you mean  by 'Polar version of the dark variant'?

**Comment by svnset** [comment]
Hello, sry for the very late reply, was quite occupied the last month.

What I mean is basically merging https://github.com/EliverLara/Nordic-Polar with this one and then having a dark/light version with both the polar highlight color (blueish) and this teal highlight color. It would be easier on the user side I guess. 

You basically did that already here https://www.gnome-look.org/p/1267246/ and have downloadable versions of exactly what I mean. My suggestion is just to make one git repo for all variants like the arc theme does or even you do in some of your other themes like https://github.com/EliverLara/Sweet

This way we could always just pull and build from one git repo for all theme variants instead of having to download a tar and check for updates manually.

Anyways still happy with the theme, great work :)

**Comment by hausofwong** [comment]
+1 for setting up separate repo for the "Nordic Bluish Accent" theme.
