### ISSUE TITLE
Application launcher in Pop_OS too dark

### ISSUE THREAD

**Issue by dylode** [EliverLara/Nordic#152]
Really love this theme. However the application launcher in Pop OS is too dark for some reason:

![dark](https://user-images.githubusercontent.com/78496445/131465517-270a5062-7452-42da-af78-0e9fdd9a7bc8.jpeg)

**Comment by Tomoghno** [comment]
> Really love this theme. However the application launcher in Pop OS is too dark for some reason:
> 
> ![dark](https://user-images.githubusercontent.com/78496445/131465517-270a5062-7452-42da-af78-0e9fdd9a7bc8.jpeg)

It is a issue with Pop!_OS.

**Comment by jmbuhr** [comment]
This is fixed after the latest update in pop-os.

**Comment by dylode** [comment]
> This is fixed after the latest update in pop-os.

Updated Pop-os and the theme. It did got better but still the selected entry is too dark. The text should be just white.

![image](https://user-images.githubusercontent.com/78496445/134812114-3832e39b-4e40-4314-9c27-24c72bf3e19b.png)


@EliverLara is your latest commit suppose to fix this issue? Tried to update the theme already but same issue.

**Comment by EliverLara** [comment]
Hi, I'm sorry for the very late response, this seems to be an issue with the way that 'Pop-OS' determinate if a theme is light or dark, and according to this clasification they apply a custom css style (wich is hard to overwrite) located in ` /usr/share/gnome-shell/extensions/pop-shell@system76.com`, so with this in mind the most feasible solution is to add `-dark` to the end of the theme folder name.

**Comment by jmbuhr** [comment]
I can confirm that this works and have been using it for a while.

**Comment by dylode** [comment]
> Hi, I'm sorry for the very late response, this seems to be an issue with the way that 'Pop-OS' determinate if a theme is light or dark, and according to this clasification they apply a custom css style (wich is hard to overwrite) located in ` /usr/share/gnome-shell/extensions/pop-shell@system76.com`, so with this in mind the most feasible solution is to add `-dark` to the end of the theme folder name.

Thank you. This fixed the issue.

**Comment by Demetrio92** [comment]
or use this: https://extensions.gnome.org/extension/19/user-themes/
