### ISSUE TITLE
Bad overview icon placement

### ISSUE THREAD

**Issue by GeneralPoxter** [EliverLara/Nordic#154]
Icons are not properly positioned in the bar in the overview:
![Screenshot from 2021-09-10 21-12-32](https://user-images.githubusercontent.com/20214615/132931440-f723e3d6-db84-48d0-a0b1-7e756a2e33bf.png)

The problem from #134 also does not seem to be resolved yet as seen in the opaque bar after updating the theme to the latest commit in master.

**Comment by EliverLara** [comment]
Hi, please take a look to [this issue](https://github.com/dracula/gtk/issues/141)

**Comment by GeneralPoxter** [comment]
Thanks, replacing gnome-shell/gnome-shell.css with gnome-shell/v40/gnome-shell.css works. :+1:
