### ISSUE TITLE
Nordic darker v40 has light buttons

### ISSUE THREAD

**Issue by bubi-luka** [EliverLara/Nordic#159]
Hi!

On updating to gnome shell 41 I have problems with your theme. The buttons on the darker theme are light and hard to read. Especially on combo box.

---

![terminal-dark](https://user-images.githubusercontent.com/1206048/133972463-79c1cdbe-ba82-4f58-bbbb-e179da56c2d1.png)
![tweaks-dark](https://user-images.githubusercontent.com/1206048/133972470-483bce89-202c-4186-9f13-1fb2422d0153.png)

---

Gnome Shell: 41.rc.1
OS: Fedora 35
Theme Version: Nordic-darker-standard-buttons-v40; 2021-08-13

**Comment by EliverLara** [comment]
HI, does this still persists? I'm using fedora 35 now and it seems to be ok:
![Captura de pantalla de 2021-11-11 14-00-22](https://user-images.githubusercontent.com/9838260/141361321-78a9de52-06c1-4862-8f52-ca2c5ad7506f.png)

**Comment by bubi-luka** [comment]
I have retested it and now it is fine. Will close the issue. Thank you!
