### ISSUE TITLE
Problem with Ubuntu Mate 18.10 with all of your themes.

### ISSUE THREAD

**Issue by mrgatos** [EliverLara/Nordic#16]
Hello.I also commented in your Sweet theme and you told me to post here. The problem is this : I install the theme via Appearance (mate's tool), but when i use the specific theme it says : This theme will not look as intended because the required window manager theme "Theme name" is not installed..following up with a question mark icon in the Appearance tab. I also tried installing some of your themes manually but the problem persists. If i use Window Borders from another theme, it will work just fine but that ruins the feeling of having your whole theme package installed.

**Comment by jinxidoo** [comment]
Third user reporting that I also experience this issue on Ubuntu MATE 18.10

**Comment by EliverLara** [comment]
I'll add the metacity theme ASAP

**Comment by mateusdeap** [comment]
Any updates? Have the same issue in 18.04.2. Should we download one of the other files in gnome-look or the fix has not come yet?

**Comment by EliverLara** [comment]
I just added the metacity theme!
