### ISSUE TITLE
Extensions window is not themed.

### ISSUE THREAD

**Issue by fly2abhishek** [EliverLara/Nordic#160]
Extension window shows white background instead of dark theme.
Theme: Nordic-darker-v40, Nordic-v40
DE: GNOME 40.4

![image](https://user-images.githubusercontent.com/1158190/134772558-2d1ea628-294f-485e-a5cb-bb404876fd6f.png)

**Comment by rakshit087** [comment]
My Extensions application is themed.
Are you running Extensions as a root user?
Apps running as a root user are not themed.

![image](https://user-images.githubusercontent.com/50898928/134808459-90d1b69f-c052-4788-a4b4-0e010680d55a.png)

**Comment by fly2abhishek** [comment]
I don't think so because other theme (like Arch-dark and WhiteSur-dark) does not have this problem.

**Comment by EliverLara** [comment]
It should be fixed now :)
