### ISSUE TITLE
Applications running with root privileges are not themed, is it intended behaviour?

### ISSUE THREAD

**Issue by rakshit087** [EliverLara/Nordic#161]
The Applications running with root ('sudo') are not themed.

System Info
OS: Ubuntu 20.04.3 LTS x86_64
Kernel: 5.11.0-36-generic 
Shell: fish 3.1.0 
DE: GNOME 
WM: Mutter

I am attaching the relevant screenshots.

nautilus without sudo
![image](https://user-images.githubusercontent.com/50898928/134808659-4543526e-6a1e-4766-be6c-d9543d656843.png)

nautilus with sudo
![image](https://user-images.githubusercontent.com/50898928/134808694-49f6da84-ed8e-4d15-8824-529c5cd37ac7.png)

**Comment by dylode** [comment]
I might be wrong but sudo is a different user, so it will get the theme from another directory?

**Comment by rakshit087** [comment]
Yes! okay make sense, so to theme sudo, we have to move it in the /usr/share/themes maybe.

**Comment by dylode** [comment]
> Yes! okay make sense, so to theme sudo, we have to move it in the /usr/share/themes maybe.

That would make sense yeah. Did it work?

**Comment by rakshit087** [comment]
It worked thanks :))
Is there no other workaround?

**Comment by EliverLara** [comment]
To use themes with apps that require `sudo` , it is necessary to install the themes in `/usr/share/themes/` directory
