### ISSUE TITLE
No background color when hovering items in dock in Pop!_OS 21.04

### ISSUE THREAD

**Issue by lipowskm** [EliverLara/Nordic#165]
When hovering on items in dock there is no background color change, like in the default or other themes. Background color is changing only when application is opened and focused. I don't know if this is intended change, but is there a way to restore this functionality? I've tried looking into `gnome-shell.css` but there are no major changes under Cosmic dock entries, so I have no clue how to enable this.

**Comment by EliverLara** [comment]
It should be fixed now.
