### ISSUE TITLE
Firefox corners are not rounded

### ISSUE THREAD

**Issue by cpuccino** [EliverLara/Nordic#166]
Noticed that the corners for firefox are not rounded

![image](https://user-images.githubusercontent.com/66815398/137123993-9f02512b-e0e3-46fe-98bb-eba816d58b04.png)

As a sidenote, do you happen to know how I can open the gtk inspector with firefox? It's opening up devtools instead. Thanks.

**Comment by EliverLara** [comment]
HI, this theme does not provide rounded corners to windows.

> As a sidenote, do you happen to know how I can open the gtk inspector with firefox? It's opening up devtools instead.

Not sure about that, but you can inspect the browser UI by doing this:

open the developer tools (F12) on any page, go to options, check both of those:

1. Enable browser chrome and add-on debugging toolboxes
2. Enable remote debugging

Now you can close those tools and press Ctrl+Alt+Shift+I to Inspect the browser UI.

**Comment by cpuccino** [comment]
Oh right, sorry i think the current appearance is due to a theme.
Firefox looks like this by if there's no theme

![image](https://user-images.githubusercontent.com/66815398/142411800-3b45c30a-cc27-4361-9a70-82b5d14b5588.png)
the corners are actually rounded which is good, but the tabs looks off :(

Is this something you can help with? if not all good, I can close the issue Thanks

**Comment by cpuccino** [comment]
Oh right, sorry i think the current appearance is due to a theme.
Firefox looks like this by if there's no theme

![image](https://user-images.githubusercontent.com/66815398/142412033-6c88216e-2bbf-4b70-ab56-6fcb6e1bd704.png)


the corners are actually rounded which is good, but the colors looks off :(

Is this something you can help with? if not all good, I can close the issue

Thanks :D

**Comment by EliverLara** [comment]
Have you tried using [this](https://addons.mozilla.org/es/firefox/addon/nordictheme/) firefox theme?

**Comment by cpuccino** [comment]
@EliverLara Yea, it doesn't work unfortunately. Anyway, I forgot to close this issue. I was gonna ages ago, really sorry about that :bow:
