### ISSUE TITLE
Theme is broken

### ISSUE THREAD

**Issue by gtxg16** [EliverLara/Nordic#170]
Using Manjaro KDE btw
So when I switch from let's say, Breath2 Light to Nordic, 90% of the KDE applications, including settings, are still a light theme.
If I go to Breath2 Dark, then Nordic, it looks ok, but the dark colour looks mismatched.
Please help

Thanks
![Screenshot_20211020_173732](https://user-images.githubusercontent.com/64848274/138134791-7392d218-c9ac-4808-93d2-a4d0278f1545.png)

**Comment by EliverLara** [comment]
Hi, it seems like the color-scheme is not applied, make sure to select 'nordic' in the colors section ( appearance > color)

**Comment by itsmii** [comment]
An error has occured - Failed to adopt Nordic KDE
Don't worry though, I found a seperate color scheme that is nordic
