### ISSUE TITLE
Adwaita Colors... Please, Please, Please!

### ISSUE THREAD

**Issue by fastrizwaan** [EliverLara/Nordic#179]
Hi @EliverLara,

Most gnome users want a tad little smaller wigets than default Adwaita. Adwaita-mini and Minwaita exists but they don't look as good as yours. Nordic widgets look amazing with perfect sized widgets. Could you kindly also make an Adwaita Colored version. I don't know CSS. Still I tried to make it look like adwaita. Here are the screenshots!
![Screenshot from 2021-12-23 11-29-24](https://user-images.githubusercontent.com/1161682/147195468-249df5b9-4b76-4edc-8d8f-79db25668dcc.png)
![Screenshot from 2021-12-23 11-29-12](https://user-images.githubusercontent.com/1161682/147195477-99a56e64-d116-4a2a-8e86-5001bf6fb7c4.png)
![Screenshot from 2021-12-23 11-28-52](https://user-images.githubusercontent.com/1161682/147195489-83846786-75fc-456e-943d-fc80956edd7b.png)

Also the window buttons (minimize, maximize, close) button has too much horizontal padding. Top window is Chrome and bottom is Nautilus.
![image](https://user-images.githubusercontent.com/1161682/147195769-1f795f5b-46ac-4802-b050-d921357ffc31.png)

**Comment by toasterrepairman** [comment]
I don't speak for the owner of this repo, but the "Nord" in Nordic explicitly refers to the [Nord color scheme](https://www.nordtheme.com/), so it would be pretty strange to add a color scheme that was explicitly _not_ Nord. Plus, the GNOME team is pretty adamant about not messing with their widget design, so making an Adwaita spin on this theme would probably end up being more trouble than it's worth. 

However, this repo is licensed as GPL 3.0, which entitles you to fork it and create your own design if you choose. CSS is pretty straightforward to modify, I doubt you'd have trouble achieving your desired effect.

**Comment by fastrizwaan** [comment]
OK thanks.
