### ISSUE TITLE
Previous page button in Firefox

### ISSUE THREAD

**Issue by Umbrien** [EliverLara/Nordic#18]
Array on the button has the same color as the button

**Comment by romildo** [comment]
> Array on the button has the same color as the button

Do you mean _arrow_, right? I am also observing this. Is there a fix?

![Screenshot at 2020-03-24 09-59-50](https://user-images.githubusercontent.com/1217934/77428069-422de180-6db6-11ea-8e64-4022e70c703d.png)

**Comment by Umbrien** [comment]
Yes, mean _arrow_.
