### ISSUE TITLE
PopOS 21.10/ Nordic V40 have light part on the theme

### ISSUE THREAD

**Issue by tin-pham** [EliverLara/Nordic#180]
![image](https://user-images.githubusercontent.com/20679090/147302284-b58ab07b-ba09-49e8-9a36-715cc26448d4.png)

![image](https://user-images.githubusercontent.com/20679090/147302302-15a16892-06f1-4df3-b168-45e3480d16c7.png)

![image](https://user-images.githubusercontent.com/20679090/147302314-e5438ee9-e5e5-4305-bad4-34ae629fb454.png)

It already in dark mode, but when I change the theme to light and to dark again, It switch back to Pop Dark, not Nordic anymore. And it still have light part
![image](https://user-images.githubusercontent.com/20679090/147302354-90bc9112-4f2b-41fe-adc5-35d3d6d2e5e0.png)

**Comment by AndreBClark** [comment]
I suggest trying these following steps:
1. download and enabe the `user-themes` gnome extension from https://extensions.gnome.org/extension/19/user-themes/
2. set the shell theme to your Nordic theme of choice

**Comment by tin-pham** [comment]
Thanks it worked
