### ISSUE TITLE
Bad plasma theme in Nordic-darker look-and-feel

### ISSUE THREAD

**Issue by sebtiz13** [EliverLara/Nordic#184]
Hello, I have try the new look-and-feel `Nordic-darker` for kde released in 2.1.0, but when I select this the plasma style not use nordic style. 

It's due too bad reference here:
https://github.com/EliverLara/Nordic/blob/dba203cfe5579fe54b46718d33cbb859ffca8668/kde/plasma/look-and-feel/Nordic-darker/contents/defaults#L13-L14

This plasma style correspond of theme kde in repository https://github.com/EliverLara/Nordic-kde and unless I'm mistaken, this theme does not yet exist in darker 

## Behavior

Global theme (look-and-feel) `Nordic` selected, `Nordic` is selected
![Screenshot_20211230_171033](https://user-images.githubusercontent.com/1382368/147768765-4de25555-d8f3-4add-a9ea-80dbc0c58149.png)

Global theme (look-and-feel) `Nordic-darker` selected, `Nordic` is not selected
![Screenshot_20211230_170407](https://user-images.githubusercontent.com/1382368/147768393-d599604c-a0ba-4595-a977-13d07cbcc4c4.png)

# Fix

If I change the reference in `defaults` file the plasma style it's correctly selected
Other solution without edit the file need to manually select the `Nordic` plasma style

**Comment by EliverLara** [comment]
Hi, This is odd  since` Nordic-darker`  plasma theme [already exists](https://www.pling.com/p/1633673/)

**Comment by sebtiz13** [comment]
Oh ok my mistake, I haven't see but the darker theme are in a branch.
As i use Manjaro (Archlinux) i have install the theme with the AUR package [nordic-kde-git](https://aur.archlinux.org/packages/nordic-kde-git/) but he not download the `darker` branch. So the problem comes from this package.

I will let them know.
Thank you.
