### ISSUE TITLE
Difference between the v40 and non-v40 downloads?

### ISSUE THREAD

**Issue by lmartinez-mirror** [EliverLara/Nordic#187]
Hi, I'd like to know if there is a difference between the v40 and non-v40 downloads available under the releases page. Do the v40 packages contain everything inside their respective non-v40 packages in addition to supporting GNOME 40+? Or do they each contain conflicting files?

**Comment by EliverLara** [comment]
Hi, the files tagged with v40 provides support to gnome v40+
