### ISSUE TITLE
Nordic Darker: no slider animation on OSD in Gnome 4.1.2

### ISSUE THREAD

**Issue by bitterhalt** [EliverLara/Nordic#188]
Found small bug no biggie. I noticed in Fedora 35 that I don't have volume slider in OSD animation.
![Screenshot from 2022-01-07 21-52-23](https://user-images.githubusercontent.com/95308907/148601530-c9f31db2-7d40-4bf6-a86b-b3da26e583b3.png)

**Comment by EliverLara** [comment]
Thanks for reporting, that was fixed with 2bfc06c5efc7a33777b3dbf0afe4a71d60fb90c1

**Comment by bitterhalt** [comment]
Thanks that was fast!
