### ISSUE TITLE
The theme is not applied to all the windows

### ISSUE THREAD

**Issue by jazz-it** [EliverLara/Nordic#191]
Some windows are still light (Linux Mint Mate). Is there a fix for this yet, or is this intended behavior?

![4gVOLaJ](https://user-images.githubusercontent.com/411471/150235987-ae481ed0-0122-40a1-b575-4b390b63ce9d.png)

**Comment by EliverLara** [comment]
Hi, please take a look to https://github.com/EliverLara/Nordic/issues/161

**Comment by jazz-it** [comment]
Fixed, thanks! :+1:
