### ISSUE TITLE
Uneven icon for shutdown

### ISSUE THREAD

**Issue by jazz-it** [EliverLara/Nordic#192]
Is the icon this big intended?

![SfFEgsf](https://user-images.githubusercontent.com/411471/150236777-d5a3e3c1-3d6c-4063-8314-8fb71b8b8b40.png)

**Comment by EliverLara** [comment]
Could you test if it's not a problem with your icon theme?

**Comment by jazz-it** [comment]
I downloaded "Zafiro-Icons-Dark-Blue-f.tar.xz" from https://www.mate-look.org/p/1209330
How could I test the icon theme?

**Comment by EliverLara** [comment]
just change your icon theme to something else and see if the problem persists

**Comment by jazz-it** [comment]
> just change your icon theme to something else and see if the problem persists

If I change it to "Zafiro-Icons-Dark.tar.xz" (another instance of Zafiro Icon Theme) the problem persists. But if I change it to "Mint-Y-Dark-Aqua" (Icon Theme that comes with Linux Mint), the problem is gone:

![ecXjHc9](https://user-images.githubusercontent.com/411471/150239600-f4e8073e-128d-43a3-ac90-41f6223483a0.png)

**Comment by jazz-it** [comment]
This theme is a killer. Should be the default of most linux distros. :)
