### ISSUE TITLE
Mix of standard and non-standard buttons

### ISSUE THREAD

**Issue by eda2z** [EliverLara/Nordic#193]
I am using Nordic-bluish-accent-standard-buttons-v40 and I noticed that gnome-extensions app is using the non-standard buttons (the colored circles). I tried Nordic-standard-buttons-v40 and it is the same. I'm not sure if any other apps use the colored circle buttons.

**Comment by EliverLara** [comment]
That was fixed with 9b88fb8b557283452cff5d81027aca8df68c6294
