### ISSUE TITLE
[Cinnamon] font-size is not adaptive to system fonts

### ISSUE THREAD

**Issue by mseveritt** [EliverLara/Nordic#198]
Dear Eliver,
first of all, many thanks for your beautiful themes!
For the Cinnamon parts, for me, there is the following issue which happens particularly in Nordic and Dracula:
- Some fonts-size as for stage are fixed as 9pt/10pt and not adaptive to the system fonts as it would be in 1em, 0.9em and so on.
- If another font-size is selected in my system, e.g. 11pt, the Cinnamon part of the theme looks out of line as it does not adapt.

Is the fixed font-size intended?
If not, is it possible to change the Cinnamon theme such that it gets adaptive?
Many thanks in advance for your feedback.

**Comment by EliverLara** [comment]
Fixed with 0a0041666760d47fa74ec6fff7d3779ea7ca8877

**Comment by MinePro120** [comment]
The issue that remains after changing the font size to the system one, is that the menu's search box is configured for 9.0pt, and thus bigger sizes are clipped. Here's an example using 9.0 and 12.0pt.
![9](https://user-images.githubusercontent.com/37949795/167218194-adc2ee4a-ca60-40be-8772-c408d8966869.png)
![12](https://user-images.githubusercontent.com/37949795/167218193-076db1e6-8775-4fcd-93ae-e50c48e4cd91.png)

**Comment by MinePro120** [comment]
@EliverLara should I open a new issue?
