### ISSUE TITLE
Desktop text grey

### ISSUE THREAD

**Issue by algent-al** [EliverLara/Nordic#20]
Nice Theme.
I just installed it on Manjaro Budgie. Overall it looks nice, but there is a problem with text color for desktop icons.

![DarkWallpaper](https://user-images.githubusercontent.com/46356616/54980758-e2d0a200-4fa6-11e9-8b34-36dd40c0b598.png)        ![WhiteWallpaper](https://user-images.githubusercontent.com/46356616/54980775-efed9100-4fa6-11e9-9634-a9bec36bb2ee.png)

**Comment by algent-al** [comment]
This problem is still present.

**Comment by EliverLara** [comment]
I'm sorry, I have not been able to reproduce the issue in my current budgie environment, I will try in an environment similar to yours

**Comment by algent-al** [comment]
This is not only on Manjaro Budgie, but also on Solus Budgie that currently I am using.

This is an updated image.
![Nordic](https://user-images.githubusercontent.com/46356616/58761900-6a0f3880-8549-11e9-8f33-e188c20ca2b9.png)

These are my fonts.
![budgie-fonts](https://user-images.githubusercontent.com/46356616/58761919-a8a4f300-8549-11e9-89ed-221024f180f8.png)

**Comment by PManlio** [comment]
Hi all.
Eliver, i'm in **love** with your desktop theme and I set it in both my desktop and my laptop. While in my laptop it's working fine, in the desktop i got the same problem.
Is there any file I have to check to help you in fixing this bug?

**Comment by EliverLara** [comment]
Fixed!

**Comment by algent-al** [comment]
Thank you! I confirm that this theme is looking good. The bug is fixed. Tried on Solus Budgie.
