### ISSUE TITLE
Ubuntu 22.04 login screen issues

### ISSUE THREAD

**Issue by eddelbuettel** [EliverLara/Nordic#200]
Thanks so much for Nordic. I had been using Nord for (mostlly) Gnome Terminal and Emacs for years and more recently added this and am very happy with it.

I needed to update one laptop pre-release to Ubuntu 22.04 (as it was having graphics driver issues) and combining the (stock Ubuntu 22.04 in) dark mode with Nordic makes the login screen a little marginal.  The 'filled circles' shown for keys pressed for the password are barely visible.

Any way I could help you with this?  Not sure I can create a screenshot while 'locked'.

**Comment by EliverLara** [comment]
By now this theme does not provide any GDM theme.

**Comment by eddelbuettel** [comment]
Yes, all working fine.  One marginal issue is on 23.04 on my laptop on the login screen the message below the password prompt hinting I could also the fingerprint reader ... is a little invisible in 'dark gray on medium gray'.  Otherwise all good on both 22.10 and 23.04.
