### ISSUE TITLE
Slow animations in GTK theme

### ISSUE THREAD

**Issue by tsbarnes** [EliverLara/Nordic#201]
I love the look of this theme, but on my system (Manjaro GNOME, Intel graphics, using Xorg) the animations are slow and choppy. It's especially noticeable in comboboxes, the fade from the background color to the highlight color takes several seconds and stutters.

**Comment by tsbarnes** [comment]
I wanted to update this issue, I've switched to XFCE and it no longer occurs, so the problem seems to be GNOME Shell specific.

**Comment by tsbarnes** [comment]
Just commenting to mention that I still have this issue in GNOME Shell, even on a high-end laptop with an nVidia graphics chip.

**Comment by EliverLara** [comment]
it was fixed some time ago :)
