### ISSUE TITLE
Any plans on moving to Gnome 42's GTK 4 ?

### ISSUE THREAD

**Issue by Araly** [EliverLara/Nordic#203]
It seems like the theming for GTK 4 apps has changed and that now a theme like this one doesn't work anymore. Do you have any plans on trying to support GTK 4 ? Would theming the libadwaita theme to behave the same but with just changed colors work ? If not, do you know of any other endeavour to theme libadwaita with Nordic colors ?
Thanks

**Comment by 3nprob** [comment]
Looks like it's already happening; should be there in next release. Current master has a `gtk-4.0` folder.

**Comment by Araly** [comment]
very promising, I'll be waiting patiently then

**Comment by BirsanStefan** [comment]
![image](https://user-images.githubusercontent.com/28309532/165170299-15146485-ade9-450e-b6b1-6ac0c6b553f0.png)
I assume you are already aware, but gnome 42 shell (ubuntu 22.04) seems to need attention. The same is the case for the Sweet theme.

No rush, we all appreciate you for your work.

**Comment by AustinMcCallister** [comment]
> ![image](https://user-images.githubusercontent.com/28309532/165170299-15146485-ade9-450e-b6b1-6ac0c6b553f0.png) I assume you are already aware, but gnome 42 shell (ubuntu 22.04) seems to need attention. The same is the case for the Sweet theme.
> 
> No rush, we all appreciate you for your work.

Set libadwaita to dark mode in gnome settings and it is at least readable, just ugly. Themes probably won't get fixed until at least gnome 43 when they are supposedly adding an official theming method.

**Comment by Araly** [comment]
> > ![image](https://user-images.githubusercontent.com/28309532/165170299-15146485-ade9-450e-b6b1-6ac0c6b553f0.png) I assume you are already aware, but gnome 42 shell (ubuntu 22.04) seems to need attention. The same is the case for the Sweet theme.
> > No rush, we all appreciate you for your work.
> 
> Set libadwaita to dark mode in gnome settings and it is at least readable, just ugly. Themes probably won't get fixed until at least gnome 43 when they are supposedly adding an official theming method.

on dark mode it's readable at least yes. I know they're going to add a way to add an accent in gnome 43, but I didn't know about actual theming. It might be a while away for now but it sounds promising

**Comment by serpro69** [comment]
What fixed it for me is installing [User Themes](https://extensions.gnome.org/extension/19/user-themes/) extension.

![image](https://user-images.githubusercontent.com/22973227/174156655-2adec492-8bb2-48fc-892a-4aa4145021e5.png)

**Comment by Araly** [comment]
Using the User Themes doesn't work for me, on Arch, gnome 42.2

**Comment by EliverLara** [comment]
@Araly Could you provide a screenchot, please?, as this issue should have been resolved with the support for gnome-shell v42

**Comment by mkaito** [comment]
This applies to the shell, but is it also supposed to apply to Gnome's own apps, such as the Settings dialog?

**Comment by Araly** [comment]
![Screenshot from 2022-06-24 14-56-24](https://user-images.githubusercontent.com/24990801/175541259-2b9ff186-a74c-43b7-9a10-d8dcfabf6f8a.png)

> @Araly Could you provide a screenchot, please?, as this issue should have been resolved with the support for gnome-shell v42

as you can see, the accent color on today's date is good, but the background and most of everything is the normal gnome brownish grey. I have the User Themes extension, the AUR nordic-theme-git package. Normal GTK apps like Settings have the right colors, it's just the theme that's wonky. It also used to be more wonky, with some background colors being the gnome brownish grey, and some other backgrounds being the nord bluish grey.

**Comment by EliverLara** [comment]
@Araly please meke sure the package you're using is up to date by using the `git` version or downloading the `.tar` files [directly from gnome-look](https://www.gnome-look.org/p/1267246/)


@mkaito for the system apps in newer gnome versions (which use libadwaita) [this](https://github.com/odziom91/libadwaita-theme-changer) works as a temporary solution.

**Comment by Araly** [comment]
![Screenshot from 2022-06-24 21-57-07](https://user-images.githubusercontent.com/24990801/175659067-ef70a18f-dea5-4cdf-8a4d-e18a2d298d57.png)

here's a better image where you can see the weird mismatch between things.

**Comment by EliverLara** [comment]
@Araly Did you try downloading the .tar files [directly from gnome-look](https://www.gnome-look.org/p/1267246/)?

**Comment by Araly** [comment]
oh it works. I'm using the git AUR package. I rebooted and that did the trick. Feel free to close the comment if it's good for you too

**Comment by mkaito** [comment]
Do you publish new releases only to gnome-look, or also to github?

The -git AUR package is broken, and the author is MIA. The `nordic-theme` package is up to date with stable github releases.

**Comment by EliverLara** [comment]
> Do you publish new releases only to gnome-look, or also to github?

Yes, the latest updates are mostly released in gnome-look.

**Comment by mkaito** [comment]
Well that explains why the AUR package is so old. Consider publishing to github too?

**Comment by EliverLara** [comment]
I just published a new release now. :)

**Comment by mkaito** [comment]
Thank you very much!
