### ISSUE TITLE
Qbittorrent doesn't respect Nordic theme

### ISSUE THREAD

**Issue by aadhithbala** [EliverLara/Nordic#205]
The latest version of Qbittorrent uses Qt6, The window controls and title bar looks different now.

Before: 
![Screenshot from 2022-04-18 13-55-28](https://user-images.githubusercontent.com/91410836/164887630-6552332f-ce35-42c1-9f98-5f8604aaef57.png)

After:
![Screenshot from 2022-04-23 14-20-12](https://user-images.githubusercontent.com/91410836/164887634-8ab5426c-cd77-4978-821e-f51659f5a775.png)

**Comment by MinePro120** [comment]
Did you configure qt6 to use gtk2 themes? On Arch, you need `qt6ct` (for configuration) and `qt6gtk2` (to use your gtk2 themes on qt).

**Comment by dovahkiin711** [comment]
I configured it just now. But still it looks a bit odd compared to the previous versions. So i downgraded the software back to Qt5.



![Screenshot from 2022-05-11 15-14-33](https://user-images.githubusercontent.com/91410836/167821740-af873143-c7ce-474b-8221-a15b8866e4b4.png)
