### ISSUE TITLE
'Bluish' save buttons in std Nordic

### ISSUE THREAD

**Issue by riquezjp** [EliverLara/Nordic#206]
In the standard Nordic theme, SAVE/OPEN file dialogue windows use the 'bluish' theme button.

![Screenshot from 2022-04-23 19-22-25](https://user-images.githubusercontent.com/10734045/164936093-aaa441b7-da76-4084-8352-0f9c7eb34c58.png)

The blue colour is `#5e81ac` & I think this is part of `button.suggested-action` in `Nordic-v40/gtk-3.0/gtk-dark.css`
There are many instances of this colour in various states of `suggested-action` ~ perhaps all should be changed to `#7fb2b1` which seems to be the light sage green colour in the other dialogue highlights. (edit: in my test theme this doesn't seem to have any effect)

**Comment by EliverLara** [comment]
Hi, that's the intentional color for the suggested actions buttons.
