### ISSUE TITLE
Pamac prefs, missing bg colour for expanded options

### ISSUE THREAD

**Issue by riquezjp** [EliverLara/Nordic#207]
In Gnome pamac (manjaro), Preferences, there are several options that can be expanded with sub-options. In these cases, the list item bg's are an off-palette light grey. The hover state works correctly on these items.

![Screenshot from 2022-04-24 10-42-26](https://user-images.githubusercontent.com/10734045/164970511-d20fd701-8efb-4bde-aa34-5384aba5ddd9.png)

![Screenshot from 2022-04-24 10-48-14](https://user-images.githubusercontent.com/10734045/164970624-dd2f55d8-b1fe-439f-bc8c-d18dd1aca5f0.png)

If anyone knows the class name for these list items, please let me know,

**Comment by Rudqo** [comment]
OS [Ubuntu 22.04]
Shell version [42]

![Screenshot from 2022-05-01 00-11-08](https://user-images.githubusercontent.com/104697707/166124332-43604a7f-2a99-47b2-ab7e-253e1f89ba9a.png)
![Screenshot from 2022-05-01 00-09-33](https://user-images.githubusercontent.com/104697707/166124348-84ca3afe-3a14-4dec-a42a-e50c3880cfa2.png)

**Comment by riquezjp** [comment]
> OS [Ubuntu 22.04] Shell version [42]

@Rudqo Gnome 42 doesn't support theming yet, You should disable user-themes extension & use only the default Yaru.
There is a modified Nordic theme you can try ~ https://github.com/odziom91/libadwaita-themes
