### ISSUE TITLE
Gnome Shell Looking Odd In Gnome 42 (Pop! 22.04)

### ISSUE THREAD

**Issue by adhirajb1109** [EliverLara/Nordic#208]
When using Nordic Darker Theme with Pop! OS 22.04 (GNOME 42) shell looks really odd . Please solve this issue as soon as possible . Pictures for your reference - 
![image](https://user-images.githubusercontent.com/74768134/167906993-049852c3-485b-4c4e-a99b-2c3a1b8e8105.png)
![image](https://user-images.githubusercontent.com/74768134/167907091-98d38b1d-5bf6-45f6-b787-778c1e116baf.png)

**Comment by IceWreck** [comment]
I'm not using the shell theme, so I dont see weird stuff like this, but I am using the GTK theme which doesn't theme GTK4 apps like settings so they look out of place.

![image](https://user-images.githubusercontent.com/18102790/168411956-ecc757df-7375-4b2d-9675-4942aa607955.png)

**Comment by EliverLara** [comment]
@adhirajb1109  please meke sure the package you're using is up to date by using the `git` version or downloading the `.tar` files [directly from gnome-look](https://www.gnome-look.org/p/1267246/)


@IceWreck  for the system apps in newer gnome versions (which use libadwaita) [this](https://github.com/odziom91/libadwaita-theme-changer) works as a temporary solution.
