### ISSUE TITLE
Lack of contrast with Chromium download UI

### ISSUE THREAD

**Issue by octacian** [EliverLara/Nordic#21]
There is not enough contrast in the downloads interface in Chromium for text to be clearly visible. I assume that the background is intended to be darker, hence the lighter text. However, since it isn't, the text is not clearly visible.

![Chromium lack of contrast](https://user-images.githubusercontent.com/15371866/55042482-df610900-4fee-11e9-825f-75d8402d2cae.png)

I have noticed that other dark themes seem to have this issue with Chromium as well, so I won't be surprised if fixing this requires some change within Chromium itself (possibly a custom theme specifically for it).

The issue seems to have appeared in relation to a recent update to Chromium, so if it is helpful, I am using version 73.0.3683.75.

**Comment by EliverLara** [comment]
I have faced this also in google-chrome, but now it seems to be fixed in latest release

![Captura de pantalla de 2019-04-20 13-29-46](https://user-images.githubusercontent.com/9838260/56460979-c4c14c00-6370-11e9-8a64-845a3c6b9e8e.png)
