### ISSUE TITLE
[Xfce]Inconsistent titlebar buttons in Firefox with Nordic-standard-buttons 

### ISSUE THREAD

**Issue by geekmiki** [EliverLara/Nordic#210]
Hi,
When using the regular Nordic theme, buttons are consistent throughout the DE.
If I use Nordic-standard-buttons, then Firefox has different buttons from the rest of the DE. In Firefox, "System theme" is chosen in both scenarios.

Thanks again for the amazing work done on this theme!

**Comment by EliverLara** [comment]
Hi, could you provide a screenshot, please?

**Comment by geekmiki** [comment]
Thanks for following up.
Here are two screenshots:
-Firefox: buttons are not the same size and do not follow the color scheme when hovering (yellow, green, red)
-Thunar: buttons are slightly bigger and are colored when hovering
![Screenshot_nordic_theme_firefox](https://user-images.githubusercontent.com/4330678/174683115-b9e83201-a922-4b22-9c25-61f84986713f.png)
![Screenshot_nordic_theme_thunar](https://user-images.githubusercontent.com/4330678/174683117-79f7b089-24f6-432d-b743-7853fb43f2d1.png)

If using the standard Nordic theme, all buttons have the same appearance.

**Comment by EliverLara** [comment]
That's due to firefox uses gtk3 and thunar is using the xfwm4 theme.
