### ISSUE TITLE
[GNOME 42.2] Spacing Issues with App Folders and Search

### ISSUE THREAD

**Issue by scotabroad** [EliverLara/Nordic#211]
When opening app folders, apps do not get displayed, or if they do, only one row is visible. It also seems apps themselves have bigger icons.
![Screenshot from 2022-06-11 19-05-39](https://user-images.githubusercontent.com/65510090/173211450-4312c7b6-b1c7-450e-aebd-9f9c5d834a29.png)
![Screenshot from 2022-06-11 19-19-21](https://user-images.githubusercontent.com/65510090/173211554-d6952666-563f-4968-9c3d-c7b2db5c9761.png)

Also, when doing search, nothing gets displayed. 
![Screenshot from 2022-06-11 19-05-04](https://user-images.githubusercontent.com/65510090/173211458-088a138d-95ab-48b7-82cf-ee163c5fbab7.png)
![Screenshot from 2022-06-11 19-10-41](https://user-images.githubusercontent.com/65510090/173211496-4835d8ea-76d1-43a0-91e3-8786aa2dac31.png)

I am using the 42 branch

**Comment by EliverLara** [comment]
Hi, this problem only occurs with the `nordic` theme? Have you tried using the master branch? since it contains the latest updates to the theme.

**Comment by scotabroad** [comment]
I switched branches and things seem to be working good for now

**Comment by scotabroad** [comment]
Okay, I went back and reset my GDM login theme to be Nordic and that somehow broke my shell, producing the same problems I had earlier when I was using the 42 branch instead of master

**Comment by scotabroad** [comment]
Reverting back to the system default GDM theme seems to fix my shell problems, so the issue seems to be with GDM
