### ISSUE TITLE
Pop_Os 22.04 Cosmic

### ISSUE THREAD

**Issue by MatteoTito** [EliverLara/Nordic#212]
When applied with gnome tweaks the theme is inconsistent: in the app menu and in the spotlight the label's app are black and not readable, plus in the dock there are 2 background layers.

**Comment by EliverLara** [comment]
Hi, could you provide a screenshot please?

**Comment by MatteoTito** [comment]
Here we go
![Schermata del 2022-06-21 12-18-58](https://user-images.githubusercontent.com/55387917/174777142-526c6b82-a07f-48a0-8862-90b88031d164.png)
![Schermata del 2022-06-21 12-18-11](https://user-images.githubusercontent.com/55387917/174777189-498e025f-04f2-4dad-81c2-daa46db19188.png)
.

**Comment by mpauper** [comment]
Try to rename the nordic theme folder adding `-dark` at the end of the name. Then re-select that theme in Tweak.

**Comment by Demetrio92** [comment]
pop OS's theming tool is weird, use the extension instead: https://extensions.gnome.org/extension/19/user-themes/
