### ISSUE TITLE
No Other Desktop Managers 

### ISSUE THREAD

**Issue by HaroonRehman** [EliverLara/Nordic#218]
While we try to log in with the normal login manager it ask us to which desktop environment to use like if we have kde and gnome installed in Kali linux so it will be asked which desktop environment to use. but in your Login manager there is no option to choose which can be quite problematic.

**Comment by HaroonRehman** [comment]
> I can confirm that the session switch option does not show up using the Nordic-darker SDDM theme with KDE Plasma 5.25.1, KDE frameworks 5.95.0, QT version 5.15.5
> 
> Looking at the source for this SDDM theme the fact that there is a [SessionButton.qml](https://github.com/EliverLara/Nordic/blob/master/kde/sddm/Nordic-darker/SessionButton.qml) file seems to imply that the session picker should be there?

So What will be the solution? Are you going to add an update soon or not ?

**Comment by EliverLara** [comment]
That should be fixed now, please try updating the sddm theme.
