### ISSUE TITLE
Padding issue in nautilus

### ISSUE THREAD

**Issue by rewibec** [EliverLara/Nordic#22]
Hey, love your theme. I have a small issue on GNOME 3.32. Not sure if other versions are affected. 

Wrong padding around the home button in Nautilus.
![Screenshot from 2019-04-20 19-13-15](https://user-images.githubusercontent.com/48051345/56459769-403af180-63a1-11e9-92d9-c87c694b5fef.png)

When you have more than two folders in the navigation bar, and you hover the home button, it moves into place.
![Screenshot from 2019-04-20 19-13-32](https://user-images.githubusercontent.com/48051345/56459770-403af180-63a1-11e9-9dea-c967947a19ec.png)
![Screenshot from 2019-04-20 19-13-46](https://user-images.githubusercontent.com/48051345/56459771-403af180-63a1-11e9-9e64-0c9a153e3028.png)

**Comment by EliverLara** [comment]
Hi, thanks for reporting!, I think it's an issue exclusively for gnome 3.32, I'll check it out.

**Comment by EliverLara** [comment]
That's fixed with latest commits
