### ISSUE TITLE
[GNOME 42.x] Libadwaita layout crash

### ISSUE THREAD

**Issue by mjkim0727** [EliverLara/Nordic#220]
* libadwaita Application(GNOME Settings)

![스크린샷 2022-07-08 12-33-44](https://user-images.githubusercontent.com/78864678/177911750-fbc7ab4c-2066-47fc-9026-eee9ba22b0a8.png)

* legacy Application(GNOME Terminal)

![스크린샷 2022-07-08 12-34-37](https://user-images.githubusercontent.com/78864678/177911902-9f0019e7-792d-4629-a683-bf24f0d90a89.png)

* Theme Version - 2.2.0

**Comment by EliverLara** [comment]
That was fixed
