### ISSUE TITLE
Pop OS 22.04 Cosmic Applications Menu Theme not changing 

### ISSUE THREAD

**Issue by manojpudasaini** [EliverLara/Nordic#227]
I have applied this theme
![Screenshot from 2022-08-25 13-53-21](https://user-images.githubusercontent.com/29195401/186611505-22b51553-bdee-4999-99c2-ceb2198a6818.png)
.
and the application menu isn't being changed. I have tried the solution by adding -dark to the theme folder name, still no luck.

**Comment by cspipaon** [comment]
Same issue here, although mine looks like below - maybe because I am using Nordic Dark?
![image](https://user-images.githubusercontent.com/33868295/187733253-48ba4a8b-c7d5-4d91-8f92-ac9cae446057.png)

**Comment by C0DK** [comment]
same issue

**Comment by EliverLara** [comment]
@cspipaon please take a look to #212

**Comment by Demetrio92** [comment]
Not perfectly themed, but at least working: 
![Screenshot from 2022-12-03 23-34-32](https://user-images.githubusercontent.com/22682408/205466637-220a270a-b0fc-4673-9891-b5df1cc2b787.png)

-----
Used the extension: https://extensions.gnome.org/extension/19/user-themes/
