### ISSUE TITLE
Some switch buttons look ugly in cinnamon

### ISSUE THREAD

**Issue by thegreatyellow67** [EliverLara/Nordic#229]
Hi, I'm using Nordic GTK theme in my desktop PC witrh linux Mint 20.3 and cinnamon 5.2.7.
I realized that some switch buttons on "Statup Applications" look ugly compared with same option buttons in other windows.

![image](https://user-images.githubusercontent.com/41580754/187611026-b78bc576-dd3a-43cb-b632-1f7fb533688a.png)

![image](https://user-images.githubusercontent.com/41580754/187508591-3eff8ac0-ac6d-42b1-b1b2-858c98c271b8.png)

Is it possible to resolve this issue?
Thanks, your gtk theme is a very good job!

**Comment by thegreatyellow67** [comment]
Same issue on System Settings > Display:

![image](https://user-images.githubusercontent.com/41580754/187610812-a07af486-40fa-4caf-85d8-186b3433b2db.png)

**Comment by Readf0x** [comment]
this issue also in a few select applications when changing the libadwaita config to use nordic colors, along with the titlebar buttons disappearing.
![image](https://github.com/EliverLara/Nordic/assets/57838054/ff33cf4f-8cbb-4ef2-9bfa-359f0f7c149d)

**Comment by Markospoko** [comment]
I think I have this too but in MATE!
