### ISSUE TITLE
Events name text color in calendar app unreadable

### ISSUE THREAD

**Issue by Umesh-TIKS** [EliverLara/Nordic#232]
**Issue**
Calendar event text color is unreadable. It display dark text color on dark background color.

**System Information**
Distro - Ubuntu 22.04 LTS
Gnome Version - 42.4
Windowing System - Wayland
Theme - Nordic Darker Standard Buttons

**Normal**
![image](https://user-images.githubusercontent.com/99947680/188866349-167d1d24-2944-48da-a559-6c444ffedb9d.png)

**Hover**
![image](https://user-images.githubusercontent.com/99947680/188866476-5da13654-ff50-4781-a995-6a85c1b34201.png)

**Comment by EliverLara** [comment]
That was fixed some time ago :)
