### ISSUE TITLE
Black text on PopOS! Launcher and Applications

### ISSUE THREAD

**Issue by carolusquintus** [EliverLara/Nordic#234]
While using a mix of Nordic theme and Sweet rainbow icons, text it's showing black text.
Is there a possibility to tweak this manually on any css file?

- Launcher
![Screenshot from 2022-09-17 14-15-37](https://user-images.githubusercontent.com/7218555/190873492-a5f30aa6-e9c6-4168-860f-f41b9f2816be.png)

- Applications
![Screenshot from 2022-09-17 14-15-10](https://user-images.githubusercontent.com/7218555/190873493-2b2650e7-7a2c-4eab-ad4c-3286323e4ab5.png)

- Tweak
![Screenshot from 2022-09-17 14-22-50](https://user-images.githubusercontent.com/7218555/190873502-5fd9e2a1-1ef2-48a5-805c-de9e8744cbac.png)

- About
![Screenshot from 2022-09-17 14-30-24](https://user-images.githubusercontent.com/7218555/190873547-fa9342c4-7875-48a3-b9a8-5a10763aac57.png)

**Comment by C0DK** [comment]
How did you get the transpancy? and also how did you get the launcher to use the nord colors? mine, as well as the popups from the top right color, and selecting the date/time?

Mine are white, when i select Nord Theme.

**Comment by carolusquintus** [comment]
I guess transparency is theme's default. To get themes properly you should install:
- [GNOME Shell extensions deb package](https://ubuntu.pkgs.org/22.04/ubuntu-universe-amd64/gnome-shell-extensions_42.0-1_all.deb.html)
- [GNOME Shell integration](https://chrome.google.com/webstore/detail/gnome-shell-integration/gphhapmejobijbbhgpjhcjognlahblep?hl=en)
- [User themes extensions](https://extensions.gnome.org/extension/19/user-themes/)

In that order.

But as I didn't found a solution I prefered to change de Ubuntu 22.04.
@C0DK
