### ISSUE TITLE
Nautilus drag highlighting problem

### ISSUE THREAD

**Issue by jakbyte** [EliverLara/Nordic#24]
When I drag a file/folder over one of my bookmarks in Nautilus, I would expect it to be highlighted, but it isn't, and it's a little confusing.

![issue](https://user-images.githubusercontent.com/29505620/57181716-29969f00-6e65-11e9-9197-071d810cb5cc.png)

Thanks!

**Comment by wphyo3820** [comment]
![image](https://user-images.githubusercontent.com/42691952/62715743-eee95900-b9b5-11e9-9808-6059c2473d50.png)

I got this snippet of code from arc-theme and it seems to solve this issue.  Simple add this to gtk.css.

**Comment by wphyo3820** [comment]
@EliverLara Do you mind taking a quick look into this? Im assuming it would be a minor fix. Thank you so much!

**Comment by EliverLara** [comment]
Thank you very much for reminding me, I'll fix it, I'm sorry if I lost the thread for a long time :pray:

**Comment by wphyo3820** [comment]
![image](https://user-images.githubusercontent.com/42691952/62725664-6e812300-b9ca-11e9-8b13-daa2a9183a90.png)

Here you go.

**Comment by jakbyte** [comment]
* OS - Arch Linux
* Nautilus version - 3.32.3

**Comment by EliverLara** [comment]
That is fixed
