### ISSUE TITLE
[BUG] Dock in preview not showing up after setting the themes in gnome tweaks

### ISSUE THREAD

**Issue by DylanWaken** [EliverLara/Nordic#241]
Everything works properly except the dock on the bottom was still like default instead of in the middle as shown in the preview pictures:

Appearance:
![Screenshot from 2022-12-04 19-41-50](https://user-images.githubusercontent.com/109344556/205544669-17ce7a0a-ed0b-4d0b-ae28-f1c934576904.png)

My gnome tweak settings:
![Screenshot from 2022-12-04 19-42-05](https://user-images.githubusercontent.com/109344556/205544673-1b803bb3-a5f0-4966-9dc9-d59052e2af02.png)

This is not showing up:
![Screenshot from 2022-12-04 19-43-33](https://user-images.githubusercontent.com/109344556/205544820-50a4e459-6835-4920-ad21-399a74c7db4d.png)

**Comment by EliverLara** [comment]
Hi, to achieve that you must install the [dash-to-dock extension](https://extensions.gnome.org/extension/307/dash-to-dock/) for gnome shell.

**Comment by DylanWaken** [comment]
Thanks, issue resolved
