### ISSUE TITLE
quick settings ubuntu 22.10

### ISSUE THREAD

**Issue by zhchok** [EliverLara/Nordic#242]
![Знімок екрана з 2022-12-07 13-40-51](https://user-images.githubusercontent.com/89203890/206170675-ba1d2970-364b-420a-969a-64025394d744.png)
![Знімок екрана з 2022-12-07 13-40-16](https://user-images.githubusercontent.com/89203890/206170683-4ac57c05-ae4a-4865-b930-be74f8385a14.png)

**Comment by EliverLara** [comment]
That was fixed a few weeks ago, please make sure to download the latest version of this theme on [gnome-look](https://www.gnome-look.org/p/1267246/)
