### ISSUE TITLE
xfce 4.18 bug in thunar sidebar

### ISSUE THREAD

**Issue by mikdmst1** [EliverLara/Nordic#245]
after update xfce to 4.18, i got bug in Thunar with Nordic theme, in Sidebar of Thunar active element dont visible.
archlinux

**Comment by BrenoAV** [comment]
I'm having the same experience (Debian Testing - XFCE 4.18 - Thunar 4.18)

![thurnar-bug-4-18](https://user-images.githubusercontent.com/58391216/209993894-566120fa-440d-4e5c-94c2-3a36381f2cd6.png)

**Comment by EliverLara** [comment]
Thanks for reporting! the issue shoud be fixed now :)
