### ISSUE TITLE
Quick settings button are not quite alright (Gnome 42 or 43)

### ISSUE THREAD

**Issue by hrqmonteiro** [EliverLara/Nordic#251]
![Screenshot from 2023-01-19 08-46-45](https://user-images.githubusercontent.com/17055027/213434592-acb36f63-24b5-47cf-8ffd-21c5196643ae.png)

**Comment by EliverLara** [comment]
Hi, I'm sorry for the very late response, that issue was fixed with https://github.com/EliverLara/Nordic/commit/03dac65d5c8aa2800e49db3ffa3139c8292fd74d, please make sure to download the latest version directly from [gnome-look](https://www.pling.com/p/1267246/) or by cloning this repository
