### ISSUE TITLE
Cannot see cursor theme in gnome

### ISSUE THREAD

**Issue by gauravagnihotri** [EliverLara/Nordic#253]
As per the installation instructions, I extracted the .tar file in /usr/.themes, 
I can see the Nordic theme options in Gnome Tweak Tool for Applications and for Shell, however, the cursor menu doesn't show Nordic option.

**Comment by tunamert0** [comment]
Are you using wayland?

**Comment by gauravagnihotri** [comment]
I am using xorg

`echo $XDG_SESSION_TYPE

x11`

**Comment by DameerGamlet** [comment]
Does the cursor have a theme? Are you sure of this?

**Comment by EliverLara** [comment]
Hi, did you download the cursor theme from [gnome-look](https://www.gnome-look.org/p/1662218/)?
