### ISSUE TITLE
Incorrect display of the theme on the app bar and the status menu

### ISSUE THREAD

**Issue by norz3n** [EliverLara/Nordic#254]
Greetings. I really like the Nordic-darker theme, but I always get discouraged by 2 things when I use this theme on Gnome 43.

1. Application panel

- Gnome
![Gnome Adwaita theme dash](https://user-images.githubusercontent.com/62791474/225855980-df47eadc-443c-4b8c-9056-e660ffdf0b68.png)

- Nordic
![Gnome Nordic theme dash](https://user-images.githubusercontent.com/62791474/225856152-98b2e0ab-c4ae-46e1-948f-8a8fd0ec178c.png)

2. Status menu

- Gnome
![Gnome Adwaita theme status menu](https://user-images.githubusercontent.com/62791474/225856500-41ea16f7-6b7d-447d-afd0-35462b50a3bb.png)

- Nordic
![Gnome Nordic theme status menu](https://user-images.githubusercontent.com/62791474/225856373-b81ed9e6-474c-4cf7-b8fd-5f07914c0992.png)

I would be very happy if you can fix these problems. Otherwise, the theme is very well done

**Comment by EliverLara** [comment]
Hi, I'm sorry but what is exactly the issue you see?

**Comment by norz3n** [comment]
For some reason, when using this theme there are problems with the position of the indicator of the running application on the dash. And some black shadows (or what is it?) on inactive buttons in the Status Menu 
The theme itself is well made, but these little things are very noticeable in everyday use.
