### ISSUE TITLE
Light grey text on white background when using Polar variant

### ISSUE THREAD

**Issue by ghost** [EliverLara/Nordic#257]
![image](https://user-images.githubusercontent.com/63500907/229925510-94c4b82d-c7d6-4a25-9843-04401d7ae371.png)

Running on Mint Cinnamon.

**Comment by schaefsteven** [comment]
Having a similar problem in Thunar, running i3, tried both Nordic-Darker and Nordic-Darker-standard-buttons-v40
![thunar-error](https://github.com/EliverLara/Nordic/assets/66270901/7eeaa4ad-0b73-4abe-8cc7-e44396c2525c)

**Comment by schaefsteven** [comment]
Update: turns out I hadn't installed correctly. For i3 users, lxappearance (available in apt) seems to be a good utility that takes care of the installation details for you.
