### ISSUE TITLE
DBeaver

### ISSUE THREAD

**Issue by nvkey** [EliverLara/Nordic#258]
DBeaver Background is white
![Screenshot from 2023-04-07 16-15-20](https://user-images.githubusercontent.com/41746013/230615248-08c1bbb3-0d2f-461f-98c9-f1207a8a8140.png)

![Снимок экрана от 2023-04-07 15-50-11](https://user-images.githubusercontent.com/41746013/230615032-4c0aa400-bd77-4f9c-a486-4596a31511e7.png)

**Comment by francocalvo** [comment]
Same problem with me! It makes many menus almost unusable

**Comment by EliverLara** [comment]
Hi, it's easily fixable by renaming the theme folder and adding `-dark` at the end of the name e.g: `Nordic` -> `Nordic-dark`
