### ISSUE TITLE
Incorrect toolbar display with gnome 44.

### ISSUE THREAD

**Issue by DameerGamlet** [EliverLara/Nordic#259]
Incorrect toolbar display with gnome 44 (ubuntu 23.04).

![image](https://user-images.githubusercontent.com/74682814/234564336-8f731b50-f13d-4dd4-a0b4-7a5b822fcd54.png)
![image](https://user-images.githubusercontent.com/74682814/234564305-b4cf0461-9ec8-4708-b3ab-7477e6782049.png)

My settings
![image](https://user-images.githubusercontent.com/74682814/234564771-fc61e90d-89c8-467a-ae3b-7ecd273b1eef.png)

**Comment by DameerGamlet** [comment]
Situation: gray text on a gray background

**Comment by DameerGamlet** [comment]
If I am the only one with this problem, please give recommendations on how to fix it.

As well as installed extensions (if that's the case):
![image](https://user-images.githubusercontent.com/74682814/234567637-4265a7af-ab6e-4ee2-8944-a0f7ffb259ea.png)

**Comment by DameerGamlet** [comment]
Хочу видеть такой результат:
![image](https://user-images.githubusercontent.com/74682814/234567911-7925d724-8984-4ae0-8004-fc14bbbfe8f8.png)

**Comment by DameerGamlet** [comment]
Windowing System: x11

**Comment by psychon-night** [comment]
I also have this issue, quite disappointing because otherwise this is a fantastic theme. A fix would be wonderful

![image](https://user-images.githubusercontent.com/49412250/235308794-a3fcc593-6494-4b7d-bece-84a700d413a5.png)

**Comment by EliverLara** [comment]
Thanks for reporting :) I'm working to fix this issue, @psychon-night Are you using any gnome-shell extension?

**Comment by DameerGamlet** [comment]
Here is a list of installed extensions (even though they didn't ask me):
![image](https://user-images.githubusercontent.com/74682814/235327536-c4b44413-a9b8-4fc3-bd80-589dc042ae20.png)

**Comment by DameerGamlet** [comment]
I get the desired view of the displayed icons only on hover:
![image](https://user-images.githubusercontent.com/74682814/235327623-47749d80-e4a4-4c46-a673-5a4115261837.png)

**Comment by EliverLara** [comment]
Those issues shoul be fixed now

**Comment by DameerGamlet** [comment]
@EliverLara Yes, thank you, it's working.)
![image](https://user-images.githubusercontent.com/74682814/236531788-f7f3fbb9-b206-41ff-ac24-11659a579b02.png)
