### ISSUE TITLE
Cinnamon desktop theme

### ISSUE THREAD

**Issue by MPE2016** [EliverLara/Nordic#26]
I love this theme, and it would be perfect if it also had a cinnamon desktop theme

**Comment by m-kru** [comment]
I have tried to set it for Cinnamon. There are two issue.
1. Window buttons render in some strange way:

![nordic_cinnamon_1](https://user-images.githubusercontent.com/26227737/63639096-1451b480-c690-11e9-91e1-fb8cc52452ad.png)

2. Desktop theme is not defined:
![nordic_cinnamon_3](https://user-images.githubusercontent.com/26227737/63639110-36e3cd80-c690-11e9-8b3d-5406681cbe43.png)

 Everything else works and looks ok. After fixing above 2 issues it would look marvelously!

**Comment by EliverLara** [comment]
Added!
