### ISSUE TITLE
Gnome 44 support

### ISSUE THREAD

**Issue by maxawake** [EliverLara/Nordic#261]
Hi, 
I really love the Nordic theme for gtk and used it without any problems up till gnome 43. Now with the update to gnome 44 some of the gnome shell menus are rendered incorrectly. 
I installed the theme with the [ibadwaita-theme-changer](https://github.com/odziom91/libadwaita-theme-changer), which works well for usual gtk apps like nautilus and settings. However, the settings dropdown menu of the top bar of gnome changed and is not displayed correctly anymore 

![image](https://github.com/EliverLara/Nordic/assets/13322597/c18df1b6-6bdc-4b35-a69a-880b960d30bc)

and also the application menu looks different

![image](https://github.com/EliverLara/Nordic/assets/13322597/70412f74-7d6b-406b-933d-b275765f86ad)

I think this should not be really a big of an issue, so i really hope this beautiful theme could be further extended for gnome 44
Thanks in advance!

**Comment by EliverLara** [comment]
Hi @maxawake , it seems your using a wrong version of the theme fot¿r your OS, please meke sure the package you're using is up to date by using the git version or downloading the .tar files [directly from gnome-look](https://www.gnome-look.org/p/1267246/)
