### ISSUE TITLE
Round corner gaps between icons in Xfce 4.18.1 panels

### ISSUE THREAD

**Issue by bligidig** [EliverLara/Nordic#263]
Hi @EliverLara @kgilmer @AndreBClark 

I'm wondering why does the panel's icons has a rounded corner similar like an empty blank spot on it every time I switch to Nordic theme. I have tried different themes such as Numix, MX-Comfort, and Blackbird, but they have no issues towards the panels.. it just clean straight lines as what we most expected in panels.

Here are the screenshots showing the issue..

- **Nordic**
![nordic_theme_marked](https://github.com/EliverLara/Nordic/assets/134568353/cc7ffdd4-22bc-439d-bca7-c379cd9fc3b1)

- **Nordic-Polar**
![nordic-polar_theme_marked](https://github.com/EliverLara/Nordic/assets/134568353/373bc11f-20d1-4326-a6dc-d38a475b2713)

Here are the other themes I tried to use without any issue so far..

- Numix
![numix_theme](https://github.com/EliverLara/Nordic/assets/134568353/a7e512dd-fb2b-493a-892c-66a09e13ad3f)

- MX-Comfort
![mx-comfort_theme](https://github.com/EliverLara/Nordic/assets/134568353/4f70c794-c600-428d-b14d-a68e6ab82359)

- Blackbird
![blackbird_theme](https://github.com/EliverLara/Nordic/assets/134568353/b47c6fc6-210e-40ec-a775-3cca97c98950)

Please help me. Thank you

**Comment by bligidig** [comment]
Hi @EliverLara

Thank you so much for the fix, I appreciate it a lot. 

I have crawled all around the fixed files labeled #263, but I have no ideas at the moment how to check or test it. I have tried to re-download the theme directory, and replaced it the current directory at ~/.themes/Nordic, but I still could not see the fixed panels. I also tried to find the 'apps' directory there, but I could not find one. No luck for me yet.

Would you kindly please let me know what should I do now from here to be able to use your fixed theme? I know I might make you a bit inconvenient, but honestly speaking, this is my first time ever in life for opening an issue report on Github ;)

Thank you

**Comment by EliverLara** [comment]
Hi @bligidig did you download the newest files from [gnome-look](https://www.pling.com/p/1267246/) ?

**Comment by bligidig** [comment]
Hi @EliverLara thank you for assisting me. I finally managed to re-download all of the files in [here](https://www.opendesktop.org/p/1267246) and replace the theme files then reboot. I hope those files also the correct way to be downloaded.

The problem gone now. Thank you

In the mean time, how to mark this tread to 'solved'?
