### ISSUE TITLE
GTK 4.0 rendered windows don't show minimize/maximize/close buttons

### ISSUE THREAD

**Issue by Laertes87** [EliverLara/Nordic#266]
![screenshot-gtk4window](https://github.com/EliverLara/Nordic/assets/132786928/67ff7e68-5a5c-4145-bce1-488417bd88ae)

As you can see in the screenshot the three buttons to minimize, maximize and close the window in the upper right corner are missing in windows using gtk 4. For gtk 3 applications everything looks perfectly fine.
If this is an issue on my end, how can I fix it?

**Comment by stephanlamoureux** [comment]
Same here using Fedora/Gnome44. This theme is amazing, I hope there is a fix!

**Comment by stephanlamoureux** [comment]
@Laertes87 Ok so there is an easy fix. Use [this](https://github.com/odziom91/libadwaita-theme-changer) python script to install it and everything works. I had all of my themes inside of /usr/share/themes but for this script you need to have it in a .themes folder in your home directory.

**Comment by EliverLara** [comment]
> @Laertes87 Ok so there is an easy fix. Use this [theme changer](https://github.com/odziom91/libadwaita-theme-changer) python script to install it and everything works. I had all of my themes inside of /usr/share/themes but for this script you need to have it in a .themes folder in your home directory.
> 
> The only issue I have now is that the min/max buttons in firefox just disappear when you hover over them, but the close button works fine.


That's the fix :)
