### ISSUE TITLE
Gnome activities overview folders don't look right

### ISSUE THREAD

**Issue by stephanlamoureux** [EliverLara/Nordic#267]
![Screenshot from 2023-05-28 22-12-01](https://github.com/EliverLara/Nordic/assets/16889593/582114ce-7fe6-486b-a3b4-36cd19d2f44e)

I'm guessing they are supposed to have rounded corners but the transparency isn't working?

**Comment by EliverLara** [comment]
Hi, Are you using any extension for the transparency?

**Comment by stephanlamoureux** [comment]
I was using the blur extension but it was causing gnome to crash so I had to turn it off.  The folders still look the same, however.

![Screenshot from 2023-06-03 19-32-30](https://github.com/EliverLara/Nordic/assets/16889593/d520ad46-4b63-443c-85cc-db790e39a95f)

**Comment by EliverLara** [comment]
Fixed with 68f435861a59b370756fab82072504abb64b893c :)
