### ISSUE TITLE
Firefox min/max buttons disappear on hover

### ISSUE THREAD

**Issue by stephanlamoureux** [EliverLara/Nordic#268]
The min and max buttons disappear on hover, and the close button gets a red circle. No issues with Chrome.

![Screenshot from 2023-05-29 18-20-46](https://github.com/EliverLara/Nordic/assets/16889593/21c4f3c4-e559-445f-80d3-ee062973f702)

![Screenshot from 2023-05-29 18-21-28](https://github.com/EliverLara/Nordic/assets/16889593/189dbc7f-8d29-41b9-b009-b4b77dc8259a)

![Screenshot from 2023-05-29 18-21-24](https://github.com/EliverLara/Nordic/assets/16889593/75098a8f-544f-4de2-8c5c-c8ca5102bd61)

**Comment by EliverLara** [comment]
What firefox version are you using?

**Comment by stephanlamoureux** [comment]
This is the most recent stable version 113.0.1 and with Firefox Dev Edition as well.

**Comment by EliverLara** [comment]
It looks like you're using the flatpak version of firefox, could you corroborate that, please? you can do it by  running this on your terminal: `flatpak list`

**Comment by stephanlamoureux** [comment]
Yes, that was the case! It works correctly now with the repo version.

**Comment by stephanlamoureux** [comment]
Yes, that was the case! It works correctly now with the repo version.
