### ISSUE TITLE
File manager padding/margin off

### ISSUE THREAD

**Issue by stephanlamoureux** [EliverLara/Nordic#269]
No matter what I resize the window to, you can't stop the horizontal scroll from showing which cuts the final column of icons in half.

![Screenshot from 2023-06-03 19-12-00](https://github.com/EliverLara/Nordic/assets/16889593/f2c00e8c-a395-470b-8a8f-aed836b34d32)

**Comment by EliverLara** [comment]
Hi, Could you provide more info about your OS please?

**Comment by stephanlamoureux** [comment]
This is on Fedora 38 and GNOME 44.1 

![Screenshot from 2023-06-03 19-39-25](https://github.com/EliverLara/Nordic/assets/16889593/3314703f-1610-423f-ad80-bcb939ae2fdc)

**Comment by stephanlamoureux** [comment]
I tried using it in list view instead and I have another weird issue. I am unable to resize the name column any smaller than it is here, but I can make it larger.

![Screenshot from 2023-06-03 19-50-56](https://github.com/EliverLara/Nordic/assets/16889593/a84cd322-6c37-4104-afc3-5de7f188fc78)

**Comment by stephanlamoureux** [comment]
Pretty sure this is a GNOME 44.1 bug and not the theme.
