### ISSUE TITLE
Some of the menu buttons are invisible.

### ISSUE THREAD

**Issue by xulongwu4** [EliverLara/Nordic#27]
With the current Nordic theme on GTK 3.32, some of the menu icons for some of the applications are very hard to see. The image is an example for gvim.
![Screenshot from 2019-05-22 13:57:46](https://user-images.githubusercontent.com/16892446/58197159-a9ac6980-7c99-11e9-8b09-7556ba9a5323.png)
This also happens for libreoffice suites.
![Screenshot from 2019-05-22 13:59:18](https://user-images.githubusercontent.com/16892446/58197256-dfe9e900-7c99-11e9-8111-834242217545.png)

**Comment by EliverLara** [comment]
Hi, that seems to be an issue of your icon theme, have you tried to change it?

**Comment by xulongwu4** [comment]
I tried Papirus, Zafiro and Numix circle icon themes but the problem persists.
