### ISSUE TITLE
GNOME power menu hover effect missing

### ISSUE THREAD

**Issue by stephanlamoureux** [EliverLara/Nordic#270]
Ok, I think this is the last theme issue I have with GNOME 😎

1. The hover effect doesn't work on the arrow section of the buttons whether they are green or grey.
2. There is no hover effect on the main button portion (where it says Bluetooth etc) if they are green.

So the only hover effect I have is on the main button portion when they are grey.

GNOME 44.1 | Fedora 38 | GTK 4.10.3.3

![Screenshot from 2023-06-04 13-55-52](https://github.com/EliverLara/Nordic/assets/16889593/f27714e3-65c0-45b5-9535-08ba464e8eac)

**Comment by EliverLara** [comment]
Fixed with 4b3a6fdcc198d12d342fa8bb0a6580b084b1edf0 :)
