### ISSUE TITLE
Pop!_OS 22.04 (Gnome 42.5) Selected item on Launcher incorrectly colored?

### ISSUE THREAD

**Issue by AgingOrange** [EliverLara/Nordic#271]
Seems the colors are off for the selected item in the Launcher.

I'm using `Nordic-v40`.

![image](https://github.com/EliverLara/Nordic/assets/90155696/f56a4f4e-b658-4c76-9dd3-0bb94ed59c80)

**Comment by AgingOrange** [comment]
This problem does not occur when using `Nordic-darker-v40`.

**Comment by EliverLara** [comment]
Hi, it's easily fixable by renaming the theme folder and adding `-dark` at the end of the name e.g: `Nordic` -> `Nordic-dark`

**Comment by didli** [comment]
Note : same issue in xfce with thunar. Selected item is (almost) unreadable, as show below : 
 - - -  
![mediaklan](https://github.com/EliverLara/Nordic/assets/3301204/66322d40-0d05-4ff3-a58c-91c12d2c2e1b)
- - -

**Comment by EliverLara** [comment]
> Note : same issue in xfce with thunar (Fedora 38). Selected item is (almost) unreadable, as shown below :
> 
> ![mediaklan](https://user-images.githubusercontent.com/3301204/248570670-66322d40-0d05-4ff3-a58c-91c12d2c2e1b.png)

@didli Are you using the latest version of the theme from [gnome-look](https://www.gnome-look.org/p/1267246/) ? cause this issue seems to be reported and fixed in https://github.com/EliverLara/Nordic/issues/245

**Comment by didli** [comment]
Thanks EliverLara, indeed, issue solved. I thought the latest release would be here but I didn't expect having to look elsewhere. Your theme is great, by the way ^^
