### ISSUE TITLE
Nordic Kde - Kvantum themes not installing

### ISSUE THREAD

**Issue by lyndhurst** [EliverLara/Nordic#275]
Hi,

Installing nordic-kde global theme from system settings menu, I find that kvantum themes are not installed.

Looking at other themes folder structure, I see that they name the `Kvantum` folder with a capital `K`; maybe that is the problem... Don't take my word for it, I have no idea.

Everything else installs properly, and kvantum themes work well when downloaded and installed 'manually' using kvantum manager.

Thanks for your time.

**Comment by EliverLara** [comment]
Hi, I'm sorry for the very late response, about you problem, the global theme doesn't  install kvantum themes you must do it manually.

**Comment by lyndhurst** [comment]
Ok, thanks for the clarification, and the great theme.
