### ISSUE TITLE
Transparent Dolphin view not working

### ISSUE THREAD

**Issue by stephanlamoureux** [EliverLara/Nordic#276]
Hi, I just switched from the Sweet Kvantum theme to Nordic and now Dolphin doesn't have the blur effect. I double-checked in the Kvantum manager and the check box is selected. It was working fine before, I tried all of the variations for Nordic and it's not working on any of them.

I tried switching back to Sweet and now the blur isn't working with that one either 🤷‍♂️

Also, the nordic-bluish kvantum theme is very broken. It even stops some apps from opening. I don't have a print screen button on my keyboard so I tried using spectacle to take a screen shot of what it looks like but I can't launch it with that theme active.

I tried uninstalling/installing again and I tried the version from the KDE store and the github repo.

**Comment by stephanlamoureux** [comment]
Seems like Dolphin is all jacked up now, is there a way to reset it?

**Comment by EliverLara** [comment]
HI, I'm sorry for the very late response, Did you fix that problem?

**Comment by stephanlamoureux** [comment]
It's ok I ended up just using the normal KDE version and got rid of the kvantum one.
