### ISSUE TITLE
Synaptic Packet-Manager and MKVToolNix GUI v78.0 in Linux Mint 21.2 Cinnamon 64-bit not themed dark but bright

### ISSUE THREAD

**Issue by SingleMalt2104** [EliverLara/Nordic#279]
The default Synaptic package manager and MKVToolNix GUI v78.0 (bunkus PPA install) in LM 21.2 Cinnamon 64bit opens with a bright theme - even the default one is dark - not a dark themed one.
The theme file I imported was "Nordic.tar.xz" (v2.2.0 dated Jun 24, 2022).
I extracted the file to the folder ~/.themes/ which I created first. After that I simply activated the Nordic theme in the cinnamon theme settings menu and restarted the system afterwards.

**Comment by cxbignekoc** [comment]
Similar here Synaptic is White

OS: Linux Mint 21.2 x86_64
Kernel: 5.15.0-89-generic
WM: Compiz
WM Theme: ClearlooksRe
Theme: Nordic-darker-standard-buttons [GTK2/3]
Icons: Numix-Circle [GTK2/3]

**Comment by EliverLara** [comment]
Hi, to fully apply the theme to apps that requires `sudo` permissions it's madatory to extract the theme under `/usr/share/themes` directory

**Comment by SingleMalt2104** [comment]
@ EliverLara

After following your advice by copying your theme folder "Nordic" with sudo-rights into
`/usr/share/themes` , synaptic shows fine now with your theme after a reboot of my Linux Mint 21.2 Cinnamon system.

Alas, the latest MKVToolBix GUI v81.0 ('Milliontown') won't work this way, it still stays mostly bright and white in its GUI.

But every other GUI-tool I tested so far, i.e. Nemo, MediaInfo-GUI, Gnome Subtitles, Audacious, Rythmbox, HexChat, as some examples, now are working as you intended it to be, I think.
