### ISSUE TITLE
Breaks the workspace widget on solus

### ISSUE THREAD

**Issue by CharlesConner** [EliverLara/Nordic#28]
Hi, I really love this theme and the only thing stopping me from using it at the moment is that it breaks the work space widget on Solus

![Screenshot from 2019-05-31 10-22-46](https://user-images.githubusercontent.com/12787673/58692208-6c796300-838e-11e9-955f-76b4b758cbf6.png)
![Screenshot from 2019-05-31 10-23-37](https://user-images.githubusercontent.com/12787673/58692214-700cea00-838e-11e9-880a-84ad58ce4b59.png)

**Comment by EliverLara** [comment]
That's fixed!
