### ISSUE TITLE
Window Buttons Missing on Some Apps

### ISSUE THREAD

**Issue by scotabroad** [EliverLara/Nordic#286]
Window buttons (close, minimize, maximize) are missing for some apps. It seems to be all libadwaita apps plus a few apps that got revamped in GNOME 45. The buttons are present, just invisible.

This screenshot displays with Nordic theme enabled and the symlinks in `~/.config/gtk-4.0` to the theme files under `/usr/share/themes/Nordic/gtk-4.0` (or the Nix equivalent to this location) to enable libadwaita theming
![Screenshot from 2023-12-11 16-07-38](https://github.com/EliverLara/Nordic/assets/65510090/4f73a006-e5ad-43cb-9aad-4f334e7aa5a0)

This screenshot displays with Nordic theme enabled, but the symlinks in `~/.config/gtk-4.0` to the theme files under `/usr/share/themes/Nordic/gtk-4.0` (or the Nix equivalent to this location) to enable libadwaita theming have been removed
![Screenshot from 2023-12-11 16-14-15](https://github.com/EliverLara/Nordic/assets/65510090/795a0ac9-9994-446b-8eab-a18eee1d3847)

Note that only GNOME Terminal has the windows buttons visible

I am on NixOS unstable with GNOME 45.1, using commit [b27dffddd05c7cc05c71f2f854a3c1a3389cac91](https://github.com/EliverLara/Nordic/tree/b27dffddd05c7cc05c71f2f854a3c1a3389cac91) (I overrode the version in `nixpkgs` as it was out of date, as it used commit [e97d2bcf4494f8ab502e33d13c74b396469a42f4](https://github.com/EliverLara/Nordic/tree/e97d2bcf4494f8ab502e33d13c74b396469a42f4))

**Comment by EliverLara** [comment]
Hi, have you tried using [libadwaita-theme-changer](https://github.com/odziom91/libadwaita-theme-changer)?

**Comment by scotabroad** [comment]
I have not, although the python script seems to just link the files that I have been linking together using Home-Manager. However, it does seem I've neglected to link the `assets` folder and just did `gtk.css` and `gtk-dark.css`, which the libadwaita-theme-changer script takes care of. Adding the `assets` folder fixed my problem.
