### ISSUE TITLE
Window Control Icons (Invisible) GTK4 Windows

### ISSUE THREAD

**Issue by wiggmpk** [EliverLara/Nordic#287]
Hello everyone! Really enjoying this theme and I appreciate the effort put into creating it.

After install, following the directions provided I'm left with a Nordic themed GTK3 application window and an Adwaita themed GTK4 application window as shown below.
![image](https://github.com/EliverLara/Nordic/assets/23482399/0da24589-d1ae-4216-9122-608e6470f921)

From there I sim-linked ~/.config/gtk-4.0 directory with that of the installed Nordic/gtk-4.0 direcotry
Which gave me Nordic themed GTK4 applications windows as show below.
![image](https://github.com/EliverLara/Nordic/assets/23482399/d7be5ec1-3db8-4ca0-accd-c00ec3f79816)

As you can see it looks great, sans the window control icons ;) which are very much still there lol

Is it possible I did something incorrectly? How can I overcome the missing Window Control Icons?

![image](https://github.com/EliverLara/Nordic/assets/23482399/1966f487-01fd-4f79-b7a3-98a770bd35ce)

**Comment by wiggmpk** [comment]
I was able to correct the issue by making modifications to a local of ~/.config/gtk3.0 and ~/.config/gtk-4.0 (instead of sim-link)
gtk.css & gtk-dark.css is both directories.

Instead of "../assets" I used the fully qualified path "/usr/share/themes/Nordic/assets"
attached are the diffs
[diff-gtk3.log](https://github.com/EliverLara/Nordic/files/13720175/diff-gtk3.log)
[diff-gtk4.log](https://github.com/EliverLara/Nordic/files/13720177/diff-gtk4.log)

**Comment by Aman1337g** [comment]
> I was able to correct the issue by making modifications to a local of ~/.config/gtk3.0 and ~/.config/gtk-4.0 (instead of sim-link) gtk.css & gtk-dark.css is both directories.
> 
> Instead of "../assets" I used the fully qualified path "/usr/share/themes/Nordic/assets" attached are the diffs [diff-gtk3.log](https://github.com/EliverLara/Nordic/files/13720175/diff-gtk3.log) [diff-gtk4.log](https://github.com/EliverLara/Nordic/files/13720177/diff-gtk4.log)

Can you explain more on how to fix the issue, may through a video.

Following are the modified gtk-3.0 and gtk-4.0 folders after copying the files from Nordic-darker-v40/(gtk-3.0 and gtk-4.0) to ~/.config/(gtk-3.0 and gtk-4.0) .
[gtk.zip](https://github.com/EliverLara/Nordic/files/13799117/gtk.zip)

**Comment by EliverLara** [comment]
Hi, the easiest way to get it fully working is by using [this script](https://github.com/odziom91/libadwaita-theme-changer)

**Comment by Aman1337g** [comment]
I am currently on Ubuntu 23.10 . If i am cloning this repo and applying the theme using gnome tweak tool it is like this : 

![Screenshot from 2024-01-02 14-23-17](https://github.com/EliverLara/Nordic/assets/97891757/c4310d2d-5aff-4e3a-b8dc-b3c5d8edff59)

and if i am downloading the zip file and then applying the theme it is like this :

![Screenshot from 2024-01-02 14-24-59](https://github.com/EliverLara/Nordic/assets/97891757/dd199abd-c2e8-4848-9593-14590b735847)

In both the cases settings and nautilus have the default theme.😲

**Comment by wiggmpk** [comment]
> > I was able to correct the issue by making modifications to a local of ~/.config/gtk3.0 and ~/.config/gtk-4.0 (instead of sim-link) gtk.css & gtk-dark.css is both directories.
> > Instead of "../assets" I used the fully qualified path "/usr/share/themes/Nordic/assets" attached are the diffs [diff-gtk3.log](https://github.com/EliverLara/Nordic/files/13720175/diff-gtk3.log) [diff-gtk4.log](https://github.com/EliverLara/Nordic/files/13720177/diff-gtk4.log)
> 
> Can you explain more on how to fix the issue, may be through a video.
> 
> Following are the modified gtk-3.0 and gtk-4.0 folders after copying the files from Nordic-darker-v40/(gtk-3.0 and gtk-4.0) to ~/.config/(gtk-3.0 and gtk-4.0) . [gtk.zip](https://github.com/EliverLara/Nordic/files/13799117/gtk.zip)

Yes, I took the master zip file.
Extracted the archive and it's contents to /usr/share/themes/Nordic
I copied the ../gtk-3.0 and ../gtk-4.0 directories (and their contents) to the local user config (IE: /home/<userName>/.config/gtk-3.0/)
I applied the theme and shell theme via Gnome Tweak Tool
Restarted the display server (I would imagine logging out and back in would be sufficient)
Profit

**Comment by wiggmpk** [comment]
> I am currently on Ubuntu 23.10 . If i am cloning this repo and applying the theme using gnome tweak tool it is like this :
> 
> ![Screenshot from 2024-01-02 14-23-17](https://private-user-images.githubusercontent.com/97891757/293722903-c4310d2d-5aff-4e3a-b8dc-b3c5d8edff59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTIxMDIsIm5iZiI6MTcwNDIxMTgwMiwicGF0aCI6Ii85Nzg5MTc1Ny8yOTM3MjI5MDMtYzQzMTBkMmQtNWFmZi00ZTNhLWI4ZGMtYjNjNWQ4ZWRmZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE2MTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMjQ5ZWMyNzRmYjhhMmUxMjIxNjhiYWYwY2I2MTIzNmQ2NjA3ZDM4YTQwZTU5ZGZhMTQzYTk1ZmEzMTc5M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TNypifgt08ZiyrkRWi4dOSQLI81AVt9U_aaWyY3pQac)
> 
> and if i am downloading the zip file and then applying the theme it is like this :
> 
> ![Screenshot from 2024-01-02 14-24-59](https://private-user-images.githubusercontent.com/97891757/293723091-dd199abd-c2e8-4848-9593-14590b735847.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTIxMDIsIm5iZiI6MTcwNDIxMTgwMiwicGF0aCI6Ii85Nzg5MTc1Ny8yOTM3MjMwOTEtZGQxOTlhYmQtYzJlOC00ODQ4LTk1OTMtMTQ1OTBiNzM1ODQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE2MTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMjM0YTRiNDZlNTk0OTlkMjUzMjcwZTA4MDliZDRiODVhZDQ5ZGYyZDNkNmEzZDg2MGRmN2E1NDk2NDBlNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d942ySPwuwqEdfw7_yDZ_AIL-1ZZMqAfwxMiU3gzcXk)
> 
> In both the cases settings and nautilus have the default theme.😲

This is most likely because of the local configs for GTK3 and GTK4 in your /home/<userName>/.config directory
I would assume you're seeing the same thing I described in my initial post.

**Comment by Aman1337g** [comment]
> > I am currently on Ubuntu 23.10 . If i am cloning this repo and applying the theme using gnome tweak tool it is like this :
> > ![Screenshot from 2024-01-02 14-23-17](https://private-user-images.githubusercontent.com/97891757/293722903-c4310d2d-5aff-4e3a-b8dc-b3c5d8edff59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTIxMDIsIm5iZiI6MTcwNDIxMTgwMiwicGF0aCI6Ii85Nzg5MTc1Ny8yOTM3MjI5MDMtYzQzMTBkMmQtNWFmZi00ZTNhLWI4ZGMtYjNjNWQ4ZWRmZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE2MTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMjQ5ZWMyNzRmYjhhMmUxMjIxNjhiYWYwY2I2MTIzNmQ2NjA3ZDM4YTQwZTU5ZGZhMTQzYTk1ZmEzMTc5M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TNypifgt08ZiyrkRWi4dOSQLI81AVt9U_aaWyY3pQac)
> > and if i am downloading the zip file and then applying the theme it is like this :
> > ![Screenshot from 2024-01-02 14-24-59](https://private-user-images.githubusercontent.com/97891757/293723091-dd199abd-c2e8-4848-9593-14590b735847.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTIxMDIsIm5iZiI6MTcwNDIxMTgwMiwicGF0aCI6Ii85Nzg5MTc1Ny8yOTM3MjMwOTEtZGQxOTlhYmQtYzJlOC00ODQ4LTk1OTMtMTQ1OTBiNzM1ODQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE2MTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMjM0YTRiNDZlNTk0OTlkMjUzMjcwZTA4MDliZDRiODVhZDQ5ZGYyZDNkNmEzZDg2MGRmN2E1NDk2NDBlNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d942ySPwuwqEdfw7_yDZ_AIL-1ZZMqAfwxMiU3gzcXk)
> > In both the cases settings and nautilus have the default theme.😲
> 
> This is most likely because of the local configs for GTK3 and GTK4 in your /home/userName/.config directory I would assume you're seeing the same thing I described in my initial post.

Yes, you are right. After modifying the filepath to **/home/user_name/.theme/assets/** my problem was resolved. Thanks.. 🙂

**Comment by Aman1337g** [comment]
After applying the changes and restarting my system, by background went grey inspite, in oveview I can see the background I setted. How to fix this ?

**Comment by Aman1337g** [comment]
> > > I am currently on Ubuntu 23.10 . If i am cloning this repo and applying the theme using gnome tweak tool it is like this :
> > > ![Screenshot from 2024-01-02 14-23-17](https://private-user-images.githubusercontent.com/97891757/293722903-c4310d2d-5aff-4e3a-b8dc-b3c5d8edff59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTIxMDIsIm5iZiI6MTcwNDIxMTgwMiwicGF0aCI6Ii85Nzg5MTc1Ny8yOTM3MjI5MDMtYzQzMTBkMmQtNWFmZi00ZTNhLWI4ZGMtYjNjNWQ4ZWRmZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE2MTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMjQ5ZWMyNzRmYjhhMmUxMjIxNjhiYWYwY2I2MTIzNmQ2NjA3ZDM4YTQwZTU5ZGZhMTQzYTk1ZmEzMTc5M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TNypifgt08ZiyrkRWi4dOSQLI81AVt9U_aaWyY3pQac)
> > > and if i am downloading the zip file and then applying the theme it is like this :
> > > ![Screenshot from 2024-01-02 14-24-59](https://private-user-images.githubusercontent.com/97891757/293723091-dd199abd-c2e8-4848-9593-14590b735847.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTIxMDIsIm5iZiI6MTcwNDIxMTgwMiwicGF0aCI6Ii85Nzg5MTc1Ny8yOTM3MjMwOTEtZGQxOTlhYmQtYzJlOC00ODQ4LTk1OTMtMTQ1OTBiNzM1ODQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE2MTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMjM0YTRiNDZlNTk0OTlkMjUzMjcwZTA4MDliZDRiODVhZDQ5ZGYyZDNkNmEzZDg2MGRmN2E1NDk2NDBlNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d942ySPwuwqEdfw7_yDZ_AIL-1ZZMqAfwxMiU3gzcXk)
> > > In both the cases settings and nautilus have the default theme.😲
> > 
> > 
> > This is most likely because of the local configs for GTK3 and GTK4 in your /home/userName/.config directory I would assume you're seeing the same thing I described in my initial post.
> 
> Yes, you are right. After modifying the filepath to **/home/user_name/.theme/assets/** my problem was resolved. Thanks.. 🙂

But, after restarting the system my wallpaper is now grey, however in overview I can see the wallpaper I setted. How to fix this ?

**Comment by wiggmpk** [comment]
> > > > I am currently on Ubuntu 23.10 . If i am cloning this repo and applying the theme using gnome tweak tool it is like this :
> > > > 
> > > > and if i am downloading the zip file and then applying the theme it is like this :
> > > >
> > > > In both the cases settings and nautilus have the default theme.😲
> > > 
> > > 
> > > This is most likely because of the local configs for GTK3 and GTK4 in your /home/userName/.config directory I would assume you're seeing the same thing I described in my initial post.
> > 
> > 
> > Yes, you are right. After modifying the filepath to **/home/user_name/.theme/assets/** my problem was resolved. Thanks.. 🙂
> 
> But, after restarting the system my wallpaper is now grey, however in overview I can see the wallpaper I setted. How to fix this ?

I would just try re-applying your wallpaper however you original applied it. It should be maintained somewhere in your home directory so it was probably overwritten when you copied the gtk-3.0 and gtk-4.0 directories over.

**Comment by Aman1337g** [comment]
I tried re-applying the wallpaper but it still turned to grey. But in the oveview ( windows key + A ), the wallpaper i applied is correctly showing. I think if it is related to the css which is changing the bacground colour.
