### ISSUE TITLE
Support for GNOME 44.3, nautilus not corectly applying theme settings

### ISSUE THREAD

**Issue by DruidicBearClan** [EliverLara/Nordic#288]
Hi!

I upgraded to Ubuntu 23.04 LTS which is using GNOME v. 44.3, and it seems some applications (so far just nautilus) don't respect the theme settings.
I re-downloaded the newest version of the Nordic theme and placed it in ~/.themes.
Then enabled the theme again via the tweaks menu, both for shell and legacy applications.
I also ran the following commands:

`gsettings set org.gnome.desktop.interface gtk-theme Nordic`

and

`gsettings set org.gnome.desktop.wm.preferences theme Nordic`

I also tried to run this script:

`https://github.com/odziom91/libadwaita-theme-changer`

which first tried to remove existing gtk 4.0 css files which did not exist, then reported to have successfully installed the theme.
however, while it seems to have fixed some things it did not cause nautilus to display correctly still.

When I run nautilus from the terminal I get the following errorlog:

```
Message: 16:55:01.138: Connecting to org.freedesktop.Tracker3.Miner.Files

(org.gnome.Nautilus:209789): Gtk-WARNING **: 16:55:01.160: Theme parser error: gtk.css:5640:3-9: No property named "height"
(org.gnome.Nautilus:209789): Gtk-WARNING **: 16:55:01.174: Theme parser error: gtk.css:5640:3-9: No property named "height"
(org.gnome.Nautilus:209789): Gtk-WARNING **: 16:55:01.387: AdwGizmo 0x55b586281530 (tabboxchild) reported min width -6, but sizes must be >= 0
(org.gnome.Nautilus:209789): Gtk-WARNING **: 16:55:01.390: AdwGizmo 0x55b586281530 (tabboxchild) reported min width -6, but sizes must be >= 0
(org.gnome.Nautilus:209789): Gtk-WARNING **: 16:55:01.401: AdwGizmo 0x55b586281530 (tabboxchild) reported min width -6, but sizes must be >= 0
(org.gnome.Nautilus:209789): Gtk-WARNING **: 16:55:01.516: AdwGizmo 0x55b586281530 (tabboxchild) reported min width -6, but sizes must be >= 0
(org.gnome.Nautilus:209789): Gtk-WARNING **: 16:55:01.804: AdwGizmo 0x55b586281530 (tabboxchild) reported min width -6, but sizes must be >= 0
```
When I run a journalctl and grep everything related to nautilus I get the same logs but also the following additional logs:

```
jan 04 16:25:30 ouroboros dbus-daemon[862]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.338' (uid=1000 pid=199809 comm="/usr/bin/nautilus --gapplication-service" label="unconfined")
jan 04 16:25:30 ouroboros dbus-daemon[11314]: [session uid=1000 pid=11314] Activating service name='org.gnome.DiskUtility' requested by ':1.163' (uid=1000 pid=199809 comm="/usr/bin/nautilus --gapplication-service" label="unconfined")
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
jan 04 16:26:17 ouroboros nautilus[199809]: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
```

Just reporting this issue in the hopes it could be fixed and also to see if anyone has a solution for a temp fix? 
![Screenshot from 2024-01-04 16-52-13](https://github.com/EliverLara/Nordic/assets/62439560/5168590a-c654-4d9d-8632-614d1a5fe550)

**Comment by Aman1337g** [comment]
If you want your whole system to have nord theme, just uzip the [Nordic-darker-v40.tar.xz](https://github.com/EliverLara/Nordic/releases/download/v2.2.0/Nordic-darker-v40.tar.xz) folder to **~/.themes** folder and copy the files present in **gtk-3.0** and **gtk-4.0** (inside the nordic folder) to ~/.config/( gtk-3.0 and gtk-4.0) folders and change the occurences of **../assets/** in the **gtk.css** and **gtk-dark.css** to **/home/user_name/.themes/Nordic-darker-v40/assets**, it worked for me but there is one problem i.e. my background changed to grey.

If you want to keep your applied wallpaper then just unzip the theme to **~/.themes/** folder and apply it using gnome-tweak-tool. (in this case nordic theme is not applied to nautilus and settings app)

**Comment by DruidicBearClan** [comment]
@Aman1337g thanks for your comment. Considering this is mostly a visual issue anyways, trading it for my wallpaper being broken is not really a good fix for me, I would like to keep my wallpaper. 

Your second suggestion is indeed what I have done, and for me the settings menu is fine actually, but indeed for nautilus it is still not applied, which is what I would like to fix.

**Comment by findrakecil** [comment]
hi @DruidicBearClan 

I successfully changed the GNOME native apps theme like nautilus. I'm using GNOME 43 in Debian 12.

Here's what I did:

1. Download and extract the theme in `.themes` folder.
2. Apply theme using Gnome Tweak Tool. You may need to install it if it's not on your system. (`sudo apt install gnome-tweaks`)
3. Select Nordic in Old Application (Aplikasi lama in this screenshot)
![Cuplikan layar dari 2024-03-30 21-40-58](https://github.com/EliverLara/Nordic/assets/3760093/9d04db04-0182-4b14-be24-586e67557502)
4. Run the command from https://github.com/odziom91/libadwaita-theme-changer.

----
Here's my Nautilus in Nordic theme

![Cuplikan layar dari 2024-03-30 21-44-38](https://github.com/EliverLara/Nordic/assets/3760093/1c87761a-4924-4ac7-a786-9c90d2203c15)

**Comment by DruidicBearClan** [comment]
@findrakecil thanks for your comment. I did as described in your steps, I always have the tweak tools installed and ran the script also. It was included in my original post btw. But I will be honest somewhere down the line this problem fixed itself with an update, however it was not fixed with these steps back then. However since a month or so I no longer have the problem so this issue can now be closed! Thanks for the help anyways.

**Comment by DruidicBearClan** [comment]
Problem fixed itself somehow, I did install tweaks tool like usual, then when I had issues I ran the mentioned script. Can provide info if desired, but for now my problem is recently fixed, forgot to report back here for a bit.
