### ISSUE TITLE
issue with empty trash pop up

### ISSUE THREAD

**Issue by issam-hub** [EliverLara/Nordic#291]
i recently downloaded nordic theme and it's really awesome, but this pop up design is bothering me:
![Screenshot from 2024-01-23 09-17-56](https://github.com/EliverLara/Nordic/assets/82038486/efa6dbbd-5ef2-4076-b18f-187d038a99f6)

i want to customize it by changing some things in gtk.css, how do i find the piece of code that is styling this pop up ?

**Comment by EliverLara** [comment]
Those dialogs appearance was improved! :)
