### ISSUE TITLE
[Ubuntu 23.10, GNOME 45.2] Outline on window switching not using theme colors

### ISSUE THREAD

**Issue by gilijev** [EliverLara/Nordic#292]
When using the "Switch windows directly" shortcut (Alt-Esc by default) the outline indicating the currently selected window uses the orange from the default Ubuntu Yaru theme instead of a theme-appropriate color:

https://github.com/EliverLara/Nordic/assets/80899692/58b26ff1-22da-425b-97a3-2fa9b91f9cc0

**Comment by EliverLara** [comment]
Hi, Have you applied the gnome-shell theme?

**Comment by gilijev** [comment]
Ah, it seems I missed that step. Thank you, that solved it.
