### ISSUE TITLE
Taskbar matter

### ISSUE THREAD

**Issue by Markospoko** [EliverLara/Nordic#293]
I noticed just a visual nuisance, it's nothing significant, there are rounded corners on taskbar, you can see it at https://imgur.com/a/C0Zb1GW, I don't like that and I'd like to see taskbar as one rectangular stripe, it's going to be ideal theme with that, running programs pieces on taskbar are also "rounded", see at https://imgur.com/a/lX9yJED, it should be some "radius:" attribute I suppose but which one could it be? lastly, "show desktop" button on the most right side of taskbar has darker background color but it might be the way I sight it and should be like that, not like the rest, I don't know?, in case this piece's visually wrong, how to modify that?
all best, in advance for reply!

**Comment by EliverLara** [comment]
HI, Could you provide more details about your OS please?

**Comment by Markospoko** [comment]
Manjaro Linux MATE 23.1.3 amd64 stable release

**Comment by EliverLara** [comment]
That was fixed with 357e37fd0abc38ced6d01e5b84deac77fb19ba29 :)
