### ISSUE TITLE
Some minor bug

### ISSUE THREAD

**Issue by xDysta** [EliverLara/Nordic#3]
Can't see the previous page button on firefox 62
![capture du 2018-10-18 18-05-21](https://user-images.githubusercontent.com/25008828/47168131-656e7a80-d300-11e8-86fc-04169b18f63d.png)

A minor bug who display a black background on the search box on Google during a few seconds and disappear after the page has loaded (Nordic theme only)(can't record it sorry :/)

The check box and scroll bar are black, I don't know if it's normal or not but it's not very pretty (Nordic theme and check a random bootstrap form)
![capture du 2018-10-18 18-13-04](https://user-images.githubusercontent.com/25008828/47168562-84214100-d301-11e8-8a39-f850e461d174.png)

however, very beautiful theme :)

**Comment by EliverLara** [comment]
Hi, this is an old firefox issue with dark themes, please check more details [here](https://github.com/EliverLara/Ant/issues/25).
