### ISSUE TITLE
Question: Kvantum Nordic and Changing the Selection Color

### ISSUE THREAD

**Issue by rharmonson** [EliverLara/Nordic#302]
How do I update the selection color of the Kvantum Nordic theme from the default green to the blue like GTK Nordic bluish and Kvantum Nordic bluish? The reason I am asking is the Kvantum Nordic Bluish is significantly darker then GTK Nordic bluish. Kvantum Nordic more closely matches but the selection color needs to be changed from green to blue to match.

Is it as simple as editing a file? Which? Does it require building--hopefully not?

I am using kvantummanager and qt5ct to configure Qt themes.

Thank you! Beautiful theme.

**Comment by EliverLara** [comment]
Hi, the easiest way is by opening the `.svg` file in a text editor and replacing all the matches of the current color to the new one, in this case:

1.  Open the `Nordic` kvantum folder placed under `~/.config/Kvantum/Nordic`
2. Open the `Nordic.svg` file in a text editor
3. Find all the matches of `8fbcbb` (this is the current highlighting color of Nordic Kvantum)
4. Replace all the matches from `8fbcbb` to `81a1c1` (this is the highlight color of Nordic bluish Gtk)
5. Do the same process with the `Nordic.kvconfig` file.

**Comment by rharmonson** [comment]
Sweet! Thank you. I will do it tomorrow and follow up to this post.

**Comment by rharmonson** [comment]
Your instructions were perfect. With your guidance and experimentation, I was able to fix the incongruent text color between the GTK and Kvantum themes as well. Thank you!

Thank you for the help.
