### ISSUE TITLE
SDDM bug

### ISSUE THREAD

**Issue by FarParticul** [EliverLara/Nordic#303]
# What's the bug?
When loading in ssdm the theme just won't load complaining about not finding battery{} in some line in main.qml. If you remove it from the config, everything works, but every time you update, it's honestly annoying to have to change it.

**Comment by EliverLara** [comment]
Hi, what's your plasma version?

**Comment by FarParticul** [comment]
> Hi, what's your plasma version?

Plasma 6.0.4

**Comment by FarParticul** [comment]
I wanted to write a long time ago and only recently got to it because I'm tired of editing the config every time to make the sddm itself work

**Comment by EliverLara** [comment]
In that case it would be better to use the [sddm theme optimized for plasma 6](https://store.kde.org/p/2144235)

**Comment by FarParticul** [comment]
> In that case it would be better to use the [sddm theme optimized for plasma 6](https://store.kde.org/p/2144235)

Got it, thanks.
