### ISSUE TITLE
close maximise and minimise buttons not showing on some apps

### ISSUE THREAD

**Issue by Well-Hi** [EliverLara/Nordic#306]
![Screenshot from 2024-05-25 16-57-13](https://github.com/EliverLara/Nordic/assets/170818158/60937c33-e2d1-4824-ba2c-c3536cd0c384)
![Screenshot from 2024-05-25 16-59-05](https://github.com/EliverLara/Nordic/assets/170818158/6b95f82d-e8e7-4cbd-acea-d139dfb2d4a2)
![Screenshot from 2024-05-25 16-59-25](https://github.com/EliverLara/Nordic/assets/170818158/8ba0f9ad-0e0b-4629-9341-2182c12009af)

clicking on the area does what it's supposed to its just the buttons arent visible, they are for some apps (image viewer, etc.) but file manager and other apps like settings do not have the buttons... sorry if this is a stupid question I'm very new to this :')

**Comment by EliverLara** [comment]
HI, I'm sure that using [this script](https://github.com/odziom91/libadwaita-theme-changer) will fix your issue
