### ISSUE TITLE
KDE 6/kvantum/dolphin/status bar

### ISSUE THREAD

**Issue by n0w4y** [EliverLara/Nordic#307]
Dolphin status bar does not display disk space information correctly.

![Screenshot_20240529_235557](https://github.com/EliverLara/Nordic/assets/26310479/ba5e866f-90dc-40eb-a31e-98d23fe633c7)
_Screenshot from kvantum theme Nordic_

![Screenshot_20240529_235657](https://github.com/EliverLara/Nordic/assets/26310479/bb65a88c-1726-4250-99fa-5427b3d0c414)
_Example screenshot from kvantum theme KvFlat with correct behavior_

**Comment by EliverLara** [comment]
Fixed with 32e3176db314086cf79074bf06b936f8d62d7b15 :)
