### ISSUE TITLE
Notifications invisible

### ISSUE THREAD

**Issue by Magnus-DM** [EliverLara/Nordic#308]
Notifications have pop up but dont appear in notifications center on gnome 46. 
![image](https://github.com/EliverLara/Nordic/assets/125902826/b81e4bc8-8db9-4657-b29e-5336a54635ec)

![image](https://github.com/EliverLara/Nordic/assets/125902826/042d0e1b-ca32-41f1-aa13-5dc077a796f0)

**Comment by EliverLara** [comment]
Hi. What do you exactly mean? I don't get what's the issue

**Comment by EliverLara** [comment]
Does this happen just with Nordic? Have you try with other themes? if so it would be great if you could provide a screenshot showing how it looks with other themes, please.

**Comment by EliverLara** [comment]
I see now, Could you please provide more info about your OS?

**Comment by fmcduk** [comment]
I have the same problem. Ubuntu 24.04 running Gnome 46.

**Comment by DrNossberg** [comment]
Same issue here, Fedora 40, Gnome 46

**Comment by EliverLara** [comment]
@DrNossberg it was fixed with bf6761c, Are you using the right version of the theme for your system?

**Comment by DrNossberg** [comment]
Exact @EliverLara  ! I missed the coressponding push and didn't logged out before posting. It is indeed fixed. Thanks you very much, that's an insane reaction time !

**Comment by EliverLara** [comment]
> Shouldn't this issue be closed then ?

Yes. I'm closing it now, thanks :)
