### ISSUE TITLE
Buttons did not change

### ISSUE THREAD

**Issue by Gribovoy29** [EliverLara/Nordic#309]
![Screenshot from 2024-06-03 14-57-03](https://github.com/EliverLara/Nordic/assets/93658213/4241d12d-6391-45ce-afef-6e9329e5640d)

Hello.
I have this problem where some buttons do not want to change. I've tried to reinstall all the files, but the issue is still there.

Also how do I make the corners rounded

**Comment by EliverLara** [comment]
Hi @Gribovoy29  , it seems your using a wrong version of the theme for your OS, please meke sure the package you're using is up to date by using the git version or downloading the .tar files [directly from gnome-look](https://www.gnome-look.org/p/1267246/)

**Comment by yancelawang** [comment]
> Hi @Gribovoy29 , it seems your using a wrong version of the theme for your OS, please meke sure the package you're using is up to date by using the git version or downloading the .tar files [directly from gnome-look](https://www.gnome-look.org/p/1267246/)

May I ask? Why does it look different if i use it your them from git and by downloading it from https://www.gnome-look.org/p/1267246/ ?

**Comment by EliverLara** [comment]
> May I ask? Why does it look different if i use your theme from git and by downloading it from https://www.gnome-look.org/p/1267246/ ?

Hi @yancelawang, the difference is not between the `git` version nor the `gnome-look` version, it is because sometimes users download the theme from `github releases` wich haven't been updated for a long time now.

**Comment by yancelawang** [comment]
I see. I download by `git clone https://github.com/EliverLara/Nordic.git`. Does it the wrong way?

**Comment by EliverLara** [comment]
@yancelawang that's actually one of the correct ways to get the theme :)
