### ISSUE TITLE
Text Event Color in Calendar App same as Background Calendar Color

### ISSUE THREAD

**Issue by rizaldimaulidia** [EliverLara/Nordic#311]
Hi, I love your theme. I use Nordic Darker Theme in Ubuntu 22.04. But I have an issue with my Calendar, The event text on the calendar is the same color as the background color of the calendar, so the event text cannot be read.

I have attached a screenshot. Please fix this issue, thank you.

![338789101-0f9bdb0d-487d-42fa-bf66-196ea15e432e](https://github.com/EliverLara/Nordic/assets/8392772/5cdd9e0b-2e26-495d-8a23-e184d7cfa1e9)

**Comment by EliverLara** [comment]
Fixed with 8f7bcdb597778b7233c97423f19c936e6c5d4abf :)

**Comment by rizaldimaulidia** [comment]
Thank you very much! It's worked :100:
