### ISSUE TITLE
Can't install on Ubuntu 24.04

### ISSUE THREAD

**Issue by UnChrisGeek** [EliverLara/Nordic#312]
I've tried to install nordic on my clean Ubuntu 24.04 via Gnome tweaks and via script but none of them works

**Comment by EliverLara** [comment]
Hi, I have a few questions on your installation:

1. Where did you extract the theme?
2. How do you set your system theme to Nordic(using tweaks. terminal, etc)?
3. How does your system look while using Nordic as system theme?.

**Comment by UnChrisGeek** [comment]
Hey, turned on my pc today and it was there, everything but the folders is working now. Gnome Tweaks don't detect the darker icons.
Answering to your questions:

1: On Home/.themes
2: Gnome tweaks and the script that you let us on a link here.
3: Lemme show you
![Captura desde 2024-07-07 16-10-24](https://github.com/EliverLara/Nordic/assets/105126387/6e81bf75-94a0-4617-87ab-adbbc175f998)

How can i install the icons now?

**Comment by EliverLara** [comment]
> How can i install the icons now?

Personally I just provide [folder icons](https://www.gnome-look.org/p/1733012/) for this theme, but there are others "Nord" icon themes to choose from in gnome-look.

**Comment by UnChrisGeek** [comment]
Just installed everything, I was using the wrong folder for the icons. Thank you very much man, it looks awesome. Saludos y gracias.
