### ISSUE TITLE
Theme partially activated

### ISSUE THREAD

**Issue by Philippe-M** [EliverLara/Nordic#313]
Hello everyone, 

I downloaded the theme last Friday directly from https://www.gnome-look.org/p/1267246/, I decompressed the files into my ~/.themes folder 

![image](https://github.com/EliverLara/Nordic/assets/4558101/ebe430c8-edd6-495a-bd5f-2779ad917cd9)

And activated it with the proposed command lines. 

gsettings set org.gnome.desktop.interface gtk-theme Nordic
gsettings set org.gnome.desktop.wm.preferences theme Nordic

Then to make sure that the theme is well taken into account, I restarted my pc. 

Unfortunately, I have the impression that there is a problem :(

![image](https://github.com/EliverLara/Nordic/assets/4558101/e434769b-2072-4b08-b3b6-252bb10a123d)

Fedora 40
Gnome 46 Wayland

**Comment by EliverLara** [comment]
Hi, first of all please make sure to download the right file version for your system(In your case the ones tagged with `-v40`), then to fix the problem in your first screenshot it's recomended to run [this script](https://github.com/odziom91/libadwaita-theme-changer) and finally for the problem in your second screenshot please make sure to have the [user-themes ](https://extensions.gnome.org/extension/19/user-themes/) extension installed, once the extension is installed just set `Nordic` as your shell theme using [tweaks](https://extensions.gnome.org/extension/19/user-themes/)

**Comment by Philippe-M** [comment]
Hi, it's ok now with python script en v40 theme.

Thank's
