### ISSUE TITLE
Window Control Button Not Displayed Correctly

### ISSUE THREAD

**Issue by yancelawang** [EliverLara/Nordic#314]
Hello. First of all, thanks for your work. I love this theme. But I have a problem with the window control buttons i.e: the close and minimize/maximize buttons don't show up because they're black in apps that use gtk 4 with a dark theme. It can be seen in the attached image.

![nordic_button](https://github.com/user-attachments/assets/b94a4331-a543-482e-b1bb-895b11fe2de7)

**Comment by EliverLara** [comment]
Hi. it's highly recommended to use [this script](https://github.com/odziom91/libadwaita-theme-changer) to get the right assets copied to the right directories

**Comment by yancelawang** [comment]
> Hi. it's highly recommended to use [this script](https://github.com/odziom91/libadwaita-theme-changer) to get the right assets copied to the right directories

Thanks a lot. I see from [the script](https://github.com/odziom91/libadwaita-theme-changer) it is necessary to copy the asset folder to folder.config.
