### ISSUE TITLE
not working on all apps..

### ISSUE THREAD

**Issue by ronovague** [EliverLara/Nordic#316]
after applying the theme on legacy apps..it would only affect terminal and firefox..but not on any other gtk apps

**Comment by EliverLara** [comment]
It would be great if you could provide a screenshot and details about your OS please

**Comment by ronovague** [comment]
> It would be great if you could provide a screenshot and details about your OS please

Mine is fedora and I talked about it on the community and it turned out that the gnome tweaks i have using only toggle the gtk3 apps and not the gtk4..so there is no issue in your theme..its perfect..sorry for the inconvience
