### ISSUE TITLE
Theme parsing error in bluish accent

### ISSUE THREAD

**Issue by eda2z** [EliverLara/Nordic#32]
I was experimenting with using zenity in some shell scripts and received the following errors while using Nordic-bluish-accent:

(zenity:12027): Gtk-WARNING **: 08:22:56.171: Theme parsing error: gtk.css:4053:0: Expected semicolon
(zenity:12027): Gtk-WARNING **: 08:22:56.171: Theme parsing error: gtk.css:4057:0: Expected a valid selector

I think it has to do with the comment/fix for Pantheon. The normal (greenish) theme does not have this. Thanks for a great theme.

**Comment by EliverLara** [comment]
Thanks for reporting! that's fixed with last comit.
