### ISSUE TITLE
Cinnamon sound applet completely messed up

### ISSUE THREAD

**Issue by edofe99** [EliverLara/Nordic#324]
The sound applet changes the location of play/pause buttons based on the track title lenght, causing sometimes the buttons to be overlapped with the volume bar.

**Comment by EliverLara** [comment]
Hi. Could you provide a screenshot, please?

**Comment by EliverLara** [comment]
It was fixed with 4f9ed2f42078ead8c5cf228a8cacc2d6908e27d0 :)
