### ISSUE TITLE
Themes in the screenshot!

### ISSUE THREAD

**Issue by greed-d** [EliverLara/Nordic#327]
Sorry for the skill issue but can you tell me what's the theme in the screenshot?
I downloaded `nordic-theme-git` from AUR but it doesn't look like the one in README screenshot
![image](https://github.com/user-attachments/assets/acf9683d-4e61-4754-9137-66e6393810d2)

Also the `papirus-folders-nordic` icon pack doesn't seem to have an icon for `Videos` folder.... ( If you maintain those )

**Comment by EliverLara** [comment]
Hi, it looks just like the 'Nordic' theme, you could try downloading directly from [gnome-look](https://www.gnome-look.org/p/1267246/) since it's up to date with the repo

**Comment by greed-d** [comment]
Thanks, it seems that was what I needed to do. Sorry for the inconvenience.
