### ISSUE TITLE
Weird pixel/gap color in XFCE panel

### ISSUE THREAD

**Issue by sgon00** [EliverLara/Nordic#329]
OS: Xubuntu 24.04 (xfce) (x11)
Xfce Version: 4.18
GTK Version: 3.24.41
GTK Theme: Nordic, Nordic-v40

Please check the following screenshots for the weird pixel/gap color in Xfce4 panel. The color pixels actually can change. Sometimes, they are grey. Sometimes, they are green, black, red etc.. They are not very clear in the screenshot images, but they are actually very clear to my eyes in reality. 

![theme_bug1](https://github.com/user-attachments/assets/125dfe43-ac97-4b2f-bad3-3470a29a475d)
![theme_bug2](https://github.com/user-attachments/assets/56ae1c1a-180d-44bc-8ec7-ebe4053abe24)
![theme_bug3](https://github.com/user-attachments/assets/c2dc45e8-0a8f-488e-bfc1-f42ec26748f2)

**Comment by EliverLara** [comment]
Hi, it was fixed some time ago, please take a look to #263

**Comment by sgon00** [comment]
@EliverLara thank you very much for your help. I am a new user. I downloaded the latest release from the release page. I just realized that the latest version 2.2.0 was released in 2022. I don't know what is the proper way to install the master. I tried the following:

```bash
git clone https://github.com/EliverLara/Nordic
mv -i Nordic ~/.themes/Nordic-master
```

Then select `Nordic-master` theme in settings. I can confirm that the issue is fixed in the master code. 
But I am not sure if this is the right way to use a theme and how to use other alternative darker options. 
Anyway so far, it's good. I am closing the issue. Thank you very much.

**Comment by EliverLara** [comment]
@sgon00 the easiest way to get the last releases is by downloading directly from[ gnome-look](https://www.pling.com/p/1267246/) :)

**Comment by sgon00** [comment]
@EliverLara Thank you for the tip. I thought gnome-look had fallen out of use; my mistake. When you have time, could you please update the README to include information about where to download the latest release so people won't get confused? Thank you very much for your kind help. This is one of the best themes! I hope this theme will reach more users.
