### ISSUE TITLE
Folder icons not change

### ISSUE THREAD

**Issue by LeonardoFurtado** [EliverLara/Nordic#33]
I am currently using Ubuntu 19 and my folder icons do not change. Are there any additional steps to change icons?

**Comment by EliverLara** [comment]
you must extract the folders icons under the `.icons` directory

**Comment by LeonardoFurtado** [comment]
but there are no icons in this repository.

**Comment by EliverLara** [comment]
They are availabe in [gnome-look](https://www.opendesktop.org/p/1267246/startdownload?file_id=1539375181&file_name=Nordic-Folders.tar.xz&file_type=application/x-xz&file_size=16956&url=https%3A%2F%2Fdl.opendesktop.org%2Fapi%2Ffiles%2Fdownload%2Fid%2F1539375181%2Fs%2F71ff66686b7bd77e93e2622841973531%2Ft%2F1539379169%2Fu%2F366148%2FNordic-Folders.tar.xz)

**Comment by LeonardoFurtado** [comment]
Thanks @EliverLara , Closing this issue.
