### ISSUE TITLE
Folder icon

### ISSUE THREAD

**Issue by xulongwu4** [EliverLara/Nordic#34]
Hi, thanks for your great work on this theme.

I noticed that there are some updated pictures on the Nordic theme series on gnome-look.org, e.g., https://www.gnome-look.org/p/1267246/. The folder icons in these pictures look very nice and match the color of the gtk theme. I am wondering where we can download the folder icons. The `Nordic-Folders.tar.xz` file on gnome-look.org seems pretty old and does not contain the folder icons in the pictures.

**Comment by EliverLara** [comment]
HI, [here](https://github.com/EliverLara/Nordic/files/3570454/Nordic.zip) you have the new folders icons, I'll update it ong gnome-look too.

**Comment by xulongwu4** [comment]
Thanks again for this great theme.
