### ISSUE TITLE
Bad contrast on XFCE window buttons with Nordic-Polar

### ISSUE THREAD

**Issue by bealsc** [EliverLara/Nordic#36]
Hi. Here is a link to a screenshot for clarification:

https://cdn1.imggmi.com/uploads/2019/9/2/174ac01d54104d57341ea0c085c1004a-full.png

Screenshot taken on Debian 10 with XFCE 4.12 desktop environment

**Comment by EliverLara** [comment]
Hi, that's easily fixable by going to `configuration > panel > items > window buttons > edit element > check the 'show flat buttons' checkbox `

**Comment by bealsc** [comment]
Yes that fixed it, thank you. Issue closed.
