### ISSUE TITLE
Button Highlighting Issue

### ISSUE THREAD

**Issue by wphyo3820** [EliverLara/Nordic#37]
For certain selected button elements, it is not showing any highlights to indicate that the button is being selected... such as:

![image](https://user-images.githubusercontent.com/42691952/64445897-51547880-d08c-11e9-9256-ef4f0fd2397c.png)

Notice for scale, both 100% and 200% have the same color indicator. 100% is selected but it is not being highlighted.

OS: Manjaro 18.0.4

**Comment by EliverLara** [comment]
Fixed!
