### ISSUE TITLE
Contrast on gnome-shell texts

### ISSUE THREAD

**Issue by Hexcz** [EliverLara/Nordic#38]
Hello @EliverLara, 1st of all, i think your theme is fantastic, i simply loved it, but just 1 thing that bothers me is the lack of contrast with some of gnome-shell entries, as you can see on screenshots. I'd like to know if its possible to change the color for those, thanks a lot!!!
![Captura de tela de 2019-10-23 01-42-03](https://user-images.githubusercontent.com/17841940/67358401-a104db80-f536-11e9-8a51-ec97cdc95a6d.png)
![Captura de tela de 2019-10-23 01-42-08](https://user-images.githubusercontent.com/17841940/67358409-a4986280-f536-11e9-9c11-de9f1cef8b83.png)

**Comment by Mentioum** [comment]
Same issue :)

**Comment by EliverLara** [comment]
Could you tell me what is your gnome version?

**Comment by Mentioum** [comment]
Sure.
## Prompt:
```
cat /usr/share/gnome/gnome-version.xml
```
## Output:
```
<?xml version="1.0"?>
<gnome-version>
 <platform>3</platform>
 <minor>34</minor>
 <micro>1</micro>
 <distributor>Ubuntu</distributor>
 <!--<date></date>-->
```

**Comment by Hexcz** [comment]
Exactly the same as @Mentioum, using gnome 3.34 on Pop_Os! 19.10.

**Comment by EliverLara** [comment]
Thanks for the info! I will install gnome 3.34 to fix it

**Comment by EliverLara** [comment]
@Hexcz @Mentioum Could you test if it was fixed with the last commit, please?

**Comment by Hexcz** [comment]
Thanks for all your effort @EliverLara , i'll test on the next 30 mins, kinda busy atm.

**Comment by Hexcz** [comment]
As i can see, there are no issues so far! The contrast on colors looks great. Again, thanks a lot for your time @EliverLara.
![Captura de tela de 2019-11-05 16-02-31](https://user-images.githubusercontent.com/17841940/68237575-25029d00-ffe6-11e9-82b5-0a7b415ebba5.png)
![Captura de tela de 2019-11-05 16-02-40](https://user-images.githubusercontent.com/17841940/68237576-25029d00-ffe6-11e9-8f85-a3996d2afdf6.png)
