### ISSUE TITLE
Black color in text of desktop icons of xfce4

### ISSUE THREAD

**Issue by Joshaby** [EliverLara/Nordic#39]
It would not be like putting text in this text! Already tried to change but was unsuccessful!

**Comment by EliverLara** [comment]
Hi, What do you mean? Could you provide a screenshot?

**Comment by Joshaby** [comment]
![Captura de tela_2019-10-30_20-23-16](https://user-images.githubusercontent.com/56325844/67906433-48939680-fb53-11e9-8b9b-7d9d001d7fe8.png)
