### ISSUE TITLE
Elementary OS Support

### ISSUE THREAD

**Issue by btd1337** [EliverLara/Nordic#4]
Is It possible make this theme compatible with Pantheon Shell the elementary OS desktop environment?

**Comment by EliverLara** [comment]
Hi, which elementary OS version do you mean?

**Comment by btd1337** [comment]
@EliverLara Loki and Juno

**Comment by btd1337** [comment]
For example,elementary applications allow switching between light and dark.

![captura de tela de 2018-10-24 16-34-43](https://user-images.githubusercontent.com/11943860/47456451-f0d98700-d7aa-11e8-8669-15307063b0a5.png)

![captura de tela de 2018-10-24 16-34-52](https://user-images.githubusercontent.com/11943860/47456459-f6cf6800-d7aa-11e8-8767-a3b2b24804bb.png)

**Nordic still can't switch**
![captura de tela de 2018-10-24 16-22-26](https://user-images.githubusercontent.com/11943860/47456243-58430700-d7aa-11e8-88ed-b3cd4d2ab1ff.png)

![captura de tela de 2018-10-24 16-22-45](https://user-images.githubusercontent.com/11943860/47456258-6002ab80-d7aa-11e8-9853-9d62ec1a6db3.png)

And the theme too needs small adjustments

![captura de tela de 2018-10-24 16-35-19](https://user-images.githubusercontent.com/11943860/47456556-40b84e00-d7ab-11e8-8c98-08865de00784.png)

![captura de tela de 2018-10-24 16-23-22](https://user-images.githubusercontent.com/11943860/47456561-46ae2f00-d7ab-11e8-8063-7c5494c3e5ee.png)
