### ISSUE TITLE
Light grey text on white background in Geary

### ISSUE THREAD

**Issue by ploum** [EliverLara/Nordic#42]
Geary is nearly unusable with Nordic due to light grey on white background. I've tried another dark theme (solarized dark) and Geary works well with it so I believe it's related to Nordic.

![Screenshot from 2019-11-03 19-22-39](https://user-images.githubusercontent.com/1233155/68090039-8ce2a780-fe6f-11e9-98da-a6961b0f7c1b.png)

**Comment by EliverLara** [comment]
Hi, geary v3.34.1 looks good to me:

![Captura de pantalla de 2019-11-05 11-06-19](https://user-images.githubusercontent.com/9838260/68229450-ec9a9900-ffbc-11e9-9c32-75b7e8ed6ede.png)

So, could you provide more information about your OS and geary version, please?

**Comment by ploum** [comment]
Geary 3.32 on Ubuntu 19.10. So it's probably a geary bug.

**Comment by ploum** [comment]
the next version of geary solves the problem, indeed.
