### ISSUE TITLE
Search results missing

### ISSUE THREAD

**Issue by eh8** [EliverLara/Nordic#43]
Replaced `usr/share/gnome-shell/theme/Yaru` with the `gnome-shell` folder. This had the effect of showing no apps when I tried searching for something on the application finder.

Running Ubuntu 19.10 and GNOME 3.34.

**Comment by EliverLara** [comment]
Hi, I think it's an installation issue, please make sure you install it in conventional places(`~/.themes` or `/usr/local/share/themes/`)
