### ISSUE TITLE
Wallpaper is in bad resolution

### ISSUE THREAD

**Issue by levitribeiro** [EliverLara/Nordic#44]
I absolutely love that wallpaper of the mountains, but when i checked it in the files of the theme, it was in a terrible resolution. Please, update Nordic with the wallpaper in good resolution, Nordic theme would be much better if the users could have access to the wallpaper.

**Comment by EliverLara** [comment]
Actually, it has the same resolution as the [original](https://www.pexels.com/photo/adventure-alpine-background-black-and-white-355747/) image, I only applied a color filter

**Comment by lokesh-krishna** [comment]
Where in the files can the wallpaper be found?

**Comment by EliverLara** [comment]
@lokesh-krishna  You can find the wallpaper [here](https://i.imgur.com/SBKjnxm.jpg)
