### ISSUE TITLE
hexchat has unreadable text

### ISSUE THREAD

**Issue by romildo** [EliverLara/Nordic#46]
The [`hexchat`](https://hexchat.github.io/) IRC client has almost unreadable text when presented with the nordic theme, as can be seen in the screenshots.

![hexchat-nordic-theme](https://user-images.githubusercontent.com/1217934/69144099-49ac4980-0aa9-11ea-924f-cdbd3835cc8e.png)
![hexchat-nordic-theme-3](https://user-images.githubusercontent.com/1217934/69144376-ee2e8b80-0aa9-11ea-8528-895e9c0f34dc.png)
![hexchat-nordic-theme-4](https://user-images.githubusercontent.com/1217934/69144381-f1297c00-0aa9-11ea-8805-c824683e6075.png)

**Comment by EliverLara** [comment]
You have probably selected different themes for gtk2 and gtk3, that happens frequently when you have different desktop environments.

**Comment by romildo** [comment]
> You have probably selected different themes for gtk2 and gtk3, that happens frequently when you have different desktop environments.

Right. Thanks for the observation.
