### ISSUE TITLE
Description of notifications are barely visible

### ISSUE THREAD

**Issue by yago-gt** [EliverLara/Nordic#49]
![Captura de pantalla](https://user-images.githubusercontent.com/55067980/70198076-8b193780-16ec-11ea-8626-4ab2c803670d.png)
Here the color of the text in the notification description is black and thus barely visible.
All variations of the theme are like this. It would be nice that it was another color.
(The colors are a bit different in the picture because of the color correction profile of my display)

**Comment by EliverLara** [comment]
Fixed!
