### ISSUE TITLE
Blurry minimize/maximize/close buttons

### ISSUE THREAD

**Issue by LanderN** [EliverLara/Nordic#5]
![image](https://user-images.githubusercontent.com/12765267/47441376-50866100-d7b0-11e8-818b-3c769b1fedf3.png) ![image](https://user-images.githubusercontent.com/12765267/47441405-609e4080-d7b0-11e8-9659-4d9a852c1caa.png)
Hi! Thank you for the nice theme, it integrates nicely with other Nordified applications!

I am experiencing a minor issue though: the minimize/maximize/close buttons seem blurrier than they should be (in contrast, the images in the assets folder seem perfectly crisp to me).

Any idea what could be causing this?

**Comment by LanderN** [comment]
I just realized it only happens in certain applications (e.g. Terminal and VS Code) and not in others (e.g. Settings and Google Chrome). Maybe this helps to diagnose the problem?

**Comment by EliverLara** [comment]
I think they look better now!
