### ISSUE TITLE
Option to follow the actual nord color scheme

### ISSUE THREAD

**Issue by rien333** [EliverLara/Nordic#50]
For some reason, this theme switches the nord colors `nord0` and `nord1`.  This makes it look out of place with other applications using nord. 

From `_.nord.scss` in this project:

```css
// Copyright (c) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
// Copyright (c) 2016-present Sven Greb <code@svengreb.de>
...
/// Base component color of "Polar Night".
///
/// Used for texts, *backgrounds*, carets and structuring characters like curly- and square brackets.
...
$nord0: #2e3440;

```

As you can see, `nord0` is clearly meant to be used  as the **background color**. However, this theme uses `nord1` as the background color, while that clearly is meant to be used as the background color for secondary UI elements:
```css
/// Lighter shade color of the base component color.
///
/// Used as a *lighter background color for UI elements like status bars*.
///
...
$nord1: #3b4252;
```

Why the switch up? Do you have instructions on how to switch `nord1` and `nord0`, or could you make an option to switch them (maybe keep the current theme the "light" theme, and make the one that follows the actual nord colors the "dark" theme) ?

**Comment by EliverLara** [comment]
HI, I'm sorry for the late response. I think the [darker](https://github.com/EliverLara/Nordic/tree/darker) branch contains what you're looking for, anyway, if it doesn't fit your needs you can easily adapt the colors by modifying the `gtk-3.0/_colors.scss` file and recompiling using sass.

**Comment by rien333** [comment]
No problem, and thanks for the tips!
