### ISSUE TITLE
menu bar and folder icon sugestion

### ISSUE THREAD

**Issue by denikris** [EliverLara/Nordic#51]
hi, thanks for this cool theme my OS is
xubuntu 19.10
thunar 1.8.9 (gtk3)

i make a little edit for my personal use in `gtk-3.0/gtk.css`, `gtk-3.0/gtk-3.0/gtk-dark.css` in **line 2889** and change the value `background-color: #353c4a;` which are menubar properties for gtk3+ apps like thunar and transmission.
i also make change in files `gtkrc` in **line 17** to `gtk-color-scheme = "sidebar_bg:#2e3440\ntitlebar_bg_color:#353c4a"` and `main.rc` in **line1498** to `bg[NORMAL]      = @titlebar_bg_color` inside folder `gtk-2.0` to make menubar color also changed in gtk2 apps like smplayer (qt app with gtk+ style), audacious and gpick.

so instead menubar follow the color of app background, it follow the color of window button like screenshot below
![Screenshot_2020-02-02_20-32-33](https://user-images.githubusercontent.com/16707606/73609066-90b3d080-45fc-11ea-917f-2a1f2945a864.png)

also since nordic folder icon look similar to papirus, maybe you can make symbolic icon for side-pane (sidebar) like that too
![Screenshot_2020-02-02_20-45-25](https://user-images.githubusercontent.com/16707606/73609112-fbfda280-45fc-11ea-9234-b8664cb766af.png)

**Comment by denikris** [comment]
hi, i do make a change again.
so, instead of just make menubars have the same color as window (xfwm4), i also make thunar toolbar have the same color as windows too
![Screenshot_2020-03-10_23-55-06](https://user-images.githubusercontent.com/16707606/76338226-f9444a80-632a-11ea-900c-4355a7fe429a.png)
i don't know if you make a change will break the theme for other DE or not, but here what i changes

**gtk.css** and **gtk-dark.css** (_gtk-3.0_)

line 2896 :
`background-color: #353c4a;`

last line :
```
/*thunar*/
.thunar toolbar{
  margin-top: 0px;
 /* margin-top: 0px;*/
  padding-bottom: 6px;
  padding-left: 8px;
  padding-right: 8px;
  background-color: #353c4a;
}
```

**main.rc** (_gtk-2.0_)

line 1498 :
`bg[NORMAL] = @titlebar_bg_color`


**gtkrc** (_gtk-2.0_)

line 17 :
`gtk-color-scheme = "sidebar_bg:#2e3440\ntitlebar_bg_color:#353c4a"`

i edit the files from the latest release of standard version of this theme, hope you add this for future release :-)

apparently nordic color also available in official build papirus-folder

**Comment by EliverLara** [comment]
Implemented, thanks!
