### ISSUE TITLE
WiFi selection menu is still white

### ISSUE THREAD

**Issue by Accelyte** [EliverLara/Nordic#55]
Using Nordic-Darker:
The WiFi selection menu doesn't seem to be themed?
![Screenshot from 2020-02-18 20-13-00](https://user-images.githubusercontent.com/21363469/74774966-9f50e780-528c-11ea-9e19-0142e006c0fa.png)

**Comment by irenegr** [comment]
Ubuntu 20.04
Gnome 3.36.1

After the latest Nordic Darkest update the calendar corrected but in wifi selection the problem continues.
![Screenshot from 2020-04-27 07-47-35](https://user-images.githubusercontent.com/3054512/80334977-94ea3580-885b-11ea-97b0-a058f3b48f2c.png)

**Comment by EliverLara** [comment]
That should be fixed with the last commit.
