### ISSUE TITLE
Lots of empty space above tabs when Firefox is full-screen

### ISSUE THREAD

**Issue by ok-what** [EliverLara/Nordic#56]
I have disabled the title bar and drag space in Firefox's customize settings. I'm using Linux Mint 19.3 Cinnamon.
Works as expected in windowed mode and other programs eg. the Nemo file browser work as expected in full screen. The other themes I've tried don't have this issue (Arc, Materia, default Mint theme).

windowed:
![image](https://user-images.githubusercontent.com/57720311/76160033-2e844900-612f-11ea-91b8-d26836bad505.png)
full screen:
![image](https://user-images.githubusercontent.com/57720311/76160053-52478f00-612f-11ea-8cda-a6214a75578b.png)
Arc:
![image](https://user-images.githubusercontent.com/57720311/76160087-9b97de80-612f-11ea-8b1d-b606229ffbfb.png)

**Comment by EliverLara** [comment]
Fixed!

**Comment by ok-what** [comment]
Thanks
