### ISSUE TITLE
Changing menu entries in tray menu?

### ISSUE THREAD

**Issue by DruidicBearClan** [EliverLara/Nordic#58]
Not sure if im in the right place to ask and it's not really an issue with your theme.
I'm just curious if you could point me into the right direction and help me on how to remove entries from the right side top system tray in ubuntu shell theme. 

I'm guessing its somewhere in ubuntu.css or gnome-shell.css, but im not entirely sure.
I made a post on the ubuntu forum but they couldn't help me. 
I want to be able to edit the menu entries in the default ubuntu system tray for example bluetooth, but leave bluetooth functionality itself enabled. I already have another icon for it from blueman.

this is my topic on ubuntu forum, can you please help me?
https://ubuntuforums.org/showthread.php?t=2438888
here is a screenshot of which entry and menu I mean
https://imgur.com/o5GA9rr

**Comment by EliverLara** [comment]
That cannot be managed through the gnome shell theme, maybe it could be done using some extension.
