### ISSUE TITLE
Unreadable percentage in uGet

### ISSUE THREAD

**Issue by romildo** [EliverLara/Nordic#61]
The dark foreground color on a dark background color in the percentage column in [uGet](https://ugetdm.com/) makes it unreadable.

![Screenshot_2020-04-11_07-37-29](https://user-images.githubusercontent.com/1217934/79041585-53a12700-7bc7-11ea-8b76-feb29d2481b2.png)

**Comment by EliverLara** [comment]
Fixed with last commit
