### ISSUE TITLE
Correct style of calendar in notification window

### ISSUE THREAD

**Issue by artempl** [EliverLara/Nordic#62]
Ubuntu 20.04
Gnome 3.36.1
![Screenshot from 2020-04-13 08-50-45](https://user-images.githubusercontent.com/4968093/79095780-fc848900-7d63-11ea-929a-2f823b3c2748.png)

**Comment by melachosangfleg** [comment]
Also for search tool in gnome 3.36
![Screenshot from 2020-04-25 18-25-25](https://user-images.githubusercontent.com/22974250/80284999-5ef56600-8722-11ea-8850-98a979021793.png)

**Comment by artempl** [comment]
Fixed
Thanks!
