### ISSUE TITLE
Gnome HiDPI / Titlebar button size

### ISSUE THREAD

**Issue by trevarj** [EliverLara/Nordic#64]
Hi, I'm currently using Nordic on Gnome with a 4K monitor. The titlebar buttons (minimize, maximize, close) are very small unless I use scaling. I like to keep the scaling 100%, so is there any way that I can make the buttons larger my modifying the CSS easily? Thanks

![image](https://user-images.githubusercontent.com/5448324/80364430-941ec700-888e-11ea-8233-50ffa796419b.png)

**Comment by EliverLara** [comment]
You could easily edit the correspondig `.svg` files under the `gtk-3.0/assets` folder.
