### ISSUE TITLE
Evince isn't styled on Pop!_OS 18.04

### ISSUE THREAD

**Issue by tsdye** [EliverLara/Nordic#65]
I love the Nordic theme.  Thanks for your work.

I can't use it currently because Evince isn't styled.  The window dressing is transparent and the traffic light buttons are just the standard icons.  Other application windows look great!

I'm new to Gnome themes, so please excuse any lack of clarity.

Let me know if you have questions.

**Comment by EliverLara** [comment]
Hi, Could you provide a screenshot please? and also more information about your operating system would be helpful.

**Comment by tsdye** [comment]
Aloha,

The attached screen shot shows an evince window over part of a 
ranger window.

The operating system is Ubuntu 18.04 with some tweaks applied by a 
group called System76.

Let me know if you have questions.



Eliver L. writes:

> Hi, Could you provide a screenshot please? and also more 
> information about your operating system would be helpful.


--
Thomas S. Dye
https://tsdye.online/tsdye

**Comment by EliverLara** [comment]
Sorry but there is no screenshot in your comment.

**Comment by tsdye** [comment]
![evince-not-styled](https://user-images.githubusercontent.com/125573/80746915-543e2680-8abe-11ea-8393-c51c5ab176c2.png)

**Comment by tsdye** [comment]
Hmmm.  Everything is fine on my laptop.  The problem is with my desktop computer.  And, it persists after an upgrade to Ubuntu 20.04.
Strangely, other themes work with evince on the desktop.

**Comment by tsdye** [comment]
Thanks for your patience and for a great theme.  The problem was caused by a bad symlink--user error.
