### ISSUE TITLE
Title button positions being offset when clicked with Nordic Darker

### ISSUE THREAD

**Issue by lyichi** [EliverLara/Nordic#71]
I noticed a minor issue with Nordic Darker, where the title buttons slightly offset from their original position when clicked. I only have this problem with Nordic Darker, and not with Nordic.

I tried looking in the CSS but I'm not entirely sure which part of it is causing this issue.

![Peek 2020-05-10 18-49](https://user-images.githubusercontent.com/26250202/81497281-0ad8ad00-92f0-11ea-96aa-9f491e386757.gif)

**Comment by EliverLara** [comment]
Hi, thanks for reporting! that was fixed with the last commit.

**Comment by lyichi** [comment]
Great! Thank you!
