### ISSUE TITLE
Dash to Dock probleme

### ISSUE THREAD

**Issue by CoMeister** [EliverLara/Nordic#75]
Hello,
I have installed theme and icon sets 1 month ago. At first everything was fine but now The theme is not applied at icons into the dash.
Thank you
![Screenshot from 2020-05-22 19-06-20](https://user-images.githubusercontent.com/28532431/82692125-6c3d3c00-9c5f-11ea-8816-6e7eeae65129.png)
![Screenshot from 2020-05-22 19-07-16](https://user-images.githubusercontent.com/28532431/82692171-837c2980-9c5f-11ea-9892-1d30c62f1a7c.png)

**Comment by EliverLara** [comment]
Hi, the provided icons only contain the folders icons, to complement it just edit the index.theme file and define the "inherits" key with your favorite icon theme e.g:

`Inherits=your-favorite-icon-theme,ubuntu-mono-dark,Mint-X,elementary,gnome,hicolor`
