### ISSUE TITLE
Dolphin Video Preview Not Working Properly on Kvantum Non-Solid Theme

### ISSUE THREAD

**Issue by LazyGeniusMan** [EliverLara/Nordic#76]
Hi, I want to report a bug. When I use non-solid Kvantum Theme it's make Dolphin video preview not working properly (both normal and darker variant). When I click the video preview the video is freeze, but the seekbar and sounds is working. It's working fine in solid variant (both normal and darker variant). Could you look into it ?

Screenshot
Non Solid Variant
![image](https://user-images.githubusercontent.com/58850480/82731314-24d2b080-9d30-11ea-9b5e-3be2e2e1b405.png)

Solid Variant
![image](https://user-images.githubusercontent.com/58850480/82731341-50ee3180-9d30-11ea-9735-ae6fcc651275.png)

**Comment by EliverLara** [comment]
That's and old [kvantum issue](https://github.com/tsujan/Kvantum/issues/178).
