### ISSUE TITLE
GnuCash description field is dark on dark

### ISSUE THREAD

**Issue by sebw** [EliverLara/Nordic#78]
In Gnucash, the background when editing the description is dark (#3D4455), with a black font (#000000):

![image](https://user-images.githubusercontent.com/2285094/83185787-cc365580-a12b-11ea-8e03-8dcbff32632c.png)

**Comment by sebw** [comment]
After updating the theme, the issue seems to still be present:

![image](https://user-images.githubusercontent.com/2285094/94362961-0c4c1b80-00bf-11eb-87ea-6b07f9d1e69b.png)

This is the description of a transaction in an account.

**Comment by EliverLara** [comment]
they changed some widget classes, but it's fixed with the last commit, thanks for reporting!

**Comment by sebw** [comment]
Ah nice, I was almost certain I had seen your previous patch working. Thanks for the quick fix!
