### ISSUE TITLE
Dashed Border in Built In Windows and Pop!_OS Shop background for categories 

### ISSUE THREAD

**Issue by rmansour** [EliverLara/Nordic#83]
There are two "problems" I've found: 
1. There seems to be a system-wide dashed border (probably outline) in gnome applications (see screenshot: https://imgur.com/oKMCmt1). 

2. The thumbnails of the categories inside the Pop! Shop seems to have no background colors/images (see screenshot: https://imgur.com/GyjrNph)

**Comment by pawel-szopinski** [comment]
Also, what I noticed on the second picture is the small font of app names. The name should be bigger in comparison to the developer/company name, like in the default theme.

![Screenshot from 2020-07-18 15-52-13](https://user-images.githubusercontent.com/25465830/87853989-c6c8e080-c90e-11ea-9861-15a6d3eb80ea.png)

**Comment by lfom** [comment]
1. These dashed lines mean the content can be scrolled in that direction, it is a GTK feature (some themes hide it, was it not desirable IMHO)
2. This is because Pop!_Shop uses non standard GTK color definitions but code ElementaryOS. A workaround can be found here, maybe @EliverLara wants to implement this, just for completeness:
https://github.com/jnsh/arc-theme/issues/83

**Comment by agnivade** [comment]
Re: the dashed lines, I understand that it's a GTK feature however as a user, the scrollbars are enough of an indicator to me that the content is scrollable.

Can you point me to the setting that is doing this? I disabled the `outline-style: dashed;` style but it is still showing.

**Comment by EliverLara** [comment]
@agnivade you can disable the dashed line just by setting the `background-image `property to `none` on line [581 of gtk-3.0/_drawing.scss file](https://github.com/EliverLara/Nordic/blob/138d81f289be2926989258fade6c0a805ae06baa/gtk-3.0/_drawing.scss#L581)

**Comment by agnivade** [comment]
Ooh nice, thank you!
