### ISSUE TITLE
Installation incomplete in KDE Plasma

### ISSUE THREAD

**Issue by AlexDaciuk** [EliverLara/Nordic#84]
Hi, I installed Nordic KDE using the "Get New Global Themes" in KDE System Settings, and it installed without any errors and it shows up in the Global Themes

![Screenshot_20200623_000029](https://user-images.githubusercontent.com/2780694/85356166-ac087500-b4e4-11ea-9b37-2dfb6b371b5e.png)

But it does not show up in Plasma Styles (so I can't select Nordic Solid for example)

![Screenshot_20200623_000220](https://user-images.githubusercontent.com/2780694/85356256-e7a33f00-b4e4-11ea-982f-f03b88697488.png)

It does show up in Window Decorations and Colors

Im using Arch with the latest updates

KDE Plasma Version : 5.19.2
KDE Frameworks Version : 5.71.0
QT Version : 5.15.0

**Comment by AlexDaciuk** [comment]
Here is the error that pop us when I want to install just the Plasma Style through the System Settings

[Nordic_Installation_error.txt](https://github.com/EliverLara/Nordic/files/4822566/Nordic_Installation_error.txt)

**Comment by rago666** [comment]
There is no plasma style in Nordic. Not sure about window decorations and colors.

**Comment by AlexDaciuk** [comment]
Hm, then why it shows up when you "Search for New Plasma Styles" ? 

![Screenshot_20200701_140445](https://user-images.githubusercontent.com/2780694/86271789-e5f01000-bba3-11ea-9026-196e14297957.png)

**Comment by EliverLara** [comment]
@AlexDaciuk sometimes plasma has cache issues, if you have installed it before please make sure to remove it completely.

**Comment by AlexDaciuk** [comment]
By Plasma cache you mean my own user .cache (/home/user/.cache ) ?

I use .cache in a ramfs, so it's cleaned in every reboot
