### ISSUE TITLE
Terminal background in gtk3 3.24

### ISSUE THREAD

**Issue by eda2z** [EliverLara/Nordic#88]
The other day the background in several terminal emulators stopped working if they were configured to use theme colors for foreground/background. I have Nordic-bluish-accent-standard-buttons installed in the latest Arch/Gnome and the background for tilix is black and for gnome-terminal it is 100% transparent. I saw mention of a similar problem in the Arch forums for another theme and the solution was to add a color for text_view_bg. Apparently this is now being used in gtk apps. I modified gtk.css and gtk-dark.css under gtk-3.0 to contain

@define-color text_view_bg #3b4252;

immediately after content_view_bg and this fixed the problem. I thought you may want to update your themes accordingly. I have tried other themes but I always come back to bluish/Nordic. Very nice job and thanks for your efforts.

**Comment by 0MazaHacka0** [comment]
@eda2z thank you, it helps me. also, same here, background of gnome terminal became transparent and started shaking. 5.4.67-1-MANJARO 20, GNOME 3.36.6
