### ISSUE TITLE
Make releases on github

### ISSUE THREAD

**Issue by romildo** [EliverLara/Nordic#9]
I would like to package this theme for [NixOS](https://nixos.org). It will be easier if it is released on github. Can that happen?

**Comment by EliverLara** [comment]
Cool, I'll do it ASAP!

**Comment by EliverLara** [comment]
I just release v1.2.1 to fit gnome-look versioning.

**Comment by romildo** [comment]
Thank you. I will package and submit it for NixOS.

**Comment by romildo** [comment]
It would be nice to do same with [Nordic-Polar](https://github.com/EliverLara/Nordic-Polar).

**Comment by romildo** [comment]
Here is the PR to add Nordic to NixOS: https://github.com/NixOS/nixpkgs/pull/50897
