### ISSUE TITLE
Right-Click Menu theme broken. Gnome 3.36

### ISSUE THREAD

**Issue by ghostofone1** [EliverLara/Nordic#96]
![NordicIssue](https://user-images.githubusercontent.com/60443495/97920768-eeaa4b80-1d27-11eb-8932-367b80ef8f58.PNG)
Right-click Menu doesn't match theme.

**Comment by ghostofone1** [comment]
gnome 3.38*

**Comment by EliverLara** [comment]
Hi, it looks like you haven't applied the gnome-shell theme.
